#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AbstractWidget

#include "Basic.hpp"

#include "AbstractWidget_classes.hpp"
#include "AbstractWidget_parameters.hpp"


namespace SDK
{

// Function AbstractWidget.AbstractWidget_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UAbstractWidget_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AbstractWidget_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AbstractWidget.AbstractWidget_C.ExecuteUbergraph_AbstractWidget
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAbstractWidget_C::ExecuteUbergraph_AbstractWidget(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AbstractWidget_C", "ExecuteUbergraph_AbstractWidget");

	Params::AbstractWidget_C_ExecuteUbergraph_AbstractWidget Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AbstractWidget.AbstractWidget_C.GetPercent
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  PercentValue                                           (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAbstractWidget_C::GetPercent(double* PercentValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AbstractWidget_C", "GetPercent");

	Params::AbstractWidget_C_GetPercent Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (PercentValue != nullptr)
		*PercentValue = Parms.PercentValue;
}


// Function AbstractWidget.AbstractWidget_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAbstractWidget_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AbstractWidget_C", "PreConstruct");

	Params::AbstractWidget_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AbstractWidget.AbstractWidget_C.SetPercent
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  NewParam                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAbstractWidget_C::SetPercent(double NewParam)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AbstractWidget_C", "SetPercent");

	Params::AbstractWidget_C_SetPercent Parms{};

	Parms.NewParam = NewParam;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AbstractWidget.AbstractWidget_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// struct FGeometry                        MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAbstractWidget_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AbstractWidget_C", "Tick");

	Params::AbstractWidget_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AbstractWidget.AbstractWidget_C.UpdateStyle
// (Public, BlueprintCallable, BlueprintEvent)

void UAbstractWidget_C::UpdateStyle()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AbstractWidget_C", "UpdateStyle");

	UObject::ProcessEvent(Func, nullptr);
}

}

