#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CareerMenuWidget

#include "Basic.hpp"

#include "BP_CareerMenuWidget_classes.hpp"
#include "BP_CareerMenuWidget_parameters.hpp"


namespace SDK
{

// Function BP_CareerMenuWidget.BP_CareerMenuWidget_C.BndEvt__BP_CareerMenuWidget_WBP_PlaymenuButton_Green2_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UBP_CareerMenuWidget_C::BndEvt__BP_CareerMenuWidget_WBP_PlaymenuButton_Green2_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CareerMenuWidget_C", "BndEvt__BP_CareerMenuWidget_WBP_PlaymenuButton_Green2_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CareerMenuWidget.BP_CareerMenuWidget_C.BndEvt__BP_CareerMenuWidget_WBP_PlaymenuButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UBP_CareerMenuWidget_C::BndEvt__BP_CareerMenuWidget_WBP_PlaymenuButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CareerMenuWidget_C", "BndEvt__BP_CareerMenuWidget_WBP_PlaymenuButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CareerMenuWidget.BP_CareerMenuWidget_C.BPHighlightWidget
// (Event, Public, BlueprintEvent)
// Parameters:
// class UWidget*                          Widget                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UBP_CareerMenuWidget_C::BPHighlightWidget(class UWidget* Widget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CareerMenuWidget_C", "BPHighlightWidget");

	Params::BP_CareerMenuWidget_C_BPHighlightWidget Parms{};

	Parms.Widget = Widget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_CareerMenuWidget.BP_CareerMenuWidget_C.BPOpen
// (Event, Protected, BlueprintEvent)

void UBP_CareerMenuWidget_C::BPOpen()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CareerMenuWidget_C", "BPOpen");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CareerMenuWidget.BP_CareerMenuWidget_C.CalculateCompletedTasksForLocation
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FString                           LocationID                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// double                                  Tasks                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_CareerMenuWidget_C::CalculateCompletedTasksForLocation(const class FString& LocationID, double* Tasks)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CareerMenuWidget_C", "CalculateCompletedTasksForLocation");

	Params::BP_CareerMenuWidget_C_CalculateCompletedTasksForLocation Parms{};

	Parms.LocationID = std::move(LocationID);

	UObject::ProcessEvent(Func, &Parms);

	if (Tasks != nullptr)
		*Tasks = Parms.Tasks;
}


// Function BP_CareerMenuWidget.BP_CareerMenuWidget_C.CalculateTotalProgressionPercent
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// double                                  Progression                                            (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_CareerMenuWidget_C::CalculateTotalProgressionPercent(double* Progression)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CareerMenuWidget_C", "CalculateTotalProgressionPercent");

	Params::BP_CareerMenuWidget_C_CalculateTotalProgressionPercent Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Progression != nullptr)
		*Progression = Parms.Progression;
}


// Function BP_CareerMenuWidget.BP_CareerMenuWidget_C.CalculateTotalTasksForLocation
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FString                           LocationID                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// double                                  Tasks                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_CareerMenuWidget_C::CalculateTotalTasksForLocation(const class FString& LocationID, double* Tasks)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CareerMenuWidget_C", "CalculateTotalTasksForLocation");

	Params::BP_CareerMenuWidget_C_CalculateTotalTasksForLocation Parms{};

	Parms.LocationID = std::move(LocationID);

	UObject::ProcessEvent(Func, &Parms);

	if (Tasks != nullptr)
		*Tasks = Parms.Tasks;
}


// Function BP_CareerMenuWidget.BP_CareerMenuWidget_C.CheckAchievements
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UBP_CareerMenuWidget_C::CheckAchievements()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CareerMenuWidget_C", "CheckAchievements");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CareerMenuWidget.BP_CareerMenuWidget_C.CheckUnlockedLocation
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UBP_CareerMenuWidget_C::CheckUnlockedLocation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CareerMenuWidget_C", "CheckUnlockedLocation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CareerMenuWidget.BP_CareerMenuWidget_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UBP_CareerMenuWidget_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CareerMenuWidget_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CareerMenuWidget.BP_CareerMenuWidget_C.DevUnlock
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UBP_CareerMenuWidget_C::DevUnlock()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CareerMenuWidget_C", "DevUnlock");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CareerMenuWidget.BP_CareerMenuWidget_C.ExecuteUbergraph_BP_CareerMenuWidget
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_CareerMenuWidget_C::ExecuteUbergraph_BP_CareerMenuWidget(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CareerMenuWidget_C", "ExecuteUbergraph_BP_CareerMenuWidget");

	Params::BP_CareerMenuWidget_C_ExecuteUbergraph_BP_CareerMenuWidget Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_CareerMenuWidget.BP_CareerMenuWidget_C.FocusToLevel
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FString                           LevelName                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UBP_CareerMenuWidget_C::FocusToLevel(const class FString& LevelName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CareerMenuWidget_C", "FocusToLevel");

	Params::BP_CareerMenuWidget_C_FocusToLevel Parms{};

	Parms.LevelName = std::move(LevelName);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_CareerMenuWidget.BP_CareerMenuWidget_C.GetAllLevelButtons
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// TArray<class UBP_CareerLevelButton_C*>  Array                                                  (Parm, OutParm, ContainsInstancedReference)

void UBP_CareerMenuWidget_C::GetAllLevelButtons(TArray<class UBP_CareerLevelButton_C*>* Array)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CareerMenuWidget_C", "GetAllLevelButtons");

	Params::BP_CareerMenuWidget_C_GetAllLevelButtons Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Array != nullptr)
		*Array = std::move(Parms.Array);
}


// Function BP_CareerMenuWidget.BP_CareerMenuWidget_C.GetAllTournamentButtons
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// TArray<class UBP_CareerTournamentButton_C*>Array                                                  (Parm, OutParm, ContainsInstancedReference)

void UBP_CareerMenuWidget_C::GetAllTournamentButtons(TArray<class UBP_CareerTournamentButton_C*>* Array)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CareerMenuWidget_C", "GetAllTournamentButtons");

	Params::BP_CareerMenuWidget_C_GetAllTournamentButtons Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Array != nullptr)
		*Array = std::move(Parms.Array);
}


// Function BP_CareerMenuWidget.BP_CareerMenuWidget_C.GetVisibility_0
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UBP_CareerMenuWidget_C::GetVisibility_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CareerMenuWidget_C", "GetVisibility_0");

	Params::BP_CareerMenuWidget_C_GetVisibility_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_CareerMenuWidget.BP_CareerMenuWidget_C.InitButtons
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UBP_CareerMenuWidget_C::InitButtons()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CareerMenuWidget_C", "InitButtons");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CareerMenuWidget.BP_CareerMenuWidget_C.InitIsDemo
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UBP_CareerMenuWidget_C::InitIsDemo()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CareerMenuWidget_C", "InitIsDemo");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CareerMenuWidget.BP_CareerMenuWidget_C.InitLocations
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UBP_CareerMenuWidget_C::InitLocations()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CareerMenuWidget_C", "InitLocations");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CareerMenuWidget.BP_CareerMenuWidget_C.InitPrestige
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UBP_CareerMenuWidget_C::InitPrestige()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CareerMenuWidget_C", "InitPrestige");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CareerMenuWidget.BP_CareerMenuWidget_C.InitRewards
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UBP_CareerMenuWidget_C::InitRewards()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CareerMenuWidget_C", "InitRewards");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CareerMenuWidget.BP_CareerMenuWidget_C.InpActEvt_UIGamepadDown_K2Node_InputActionEvent_1
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void UBP_CareerMenuWidget_C::InpActEvt_UIGamepadDown_K2Node_InputActionEvent_1(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CareerMenuWidget_C", "InpActEvt_UIGamepadDown_K2Node_InputActionEvent_1");

	Params::BP_CareerMenuWidget_C_InpActEvt_UIGamepadDown_K2Node_InputActionEvent_1 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_CareerMenuWidget.BP_CareerMenuWidget_C.InpActEvt_UIGamepadInteract_K2Node_InputActionEvent_3
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void UBP_CareerMenuWidget_C::InpActEvt_UIGamepadInteract_K2Node_InputActionEvent_3(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CareerMenuWidget_C", "InpActEvt_UIGamepadInteract_K2Node_InputActionEvent_3");

	Params::BP_CareerMenuWidget_C_InpActEvt_UIGamepadInteract_K2Node_InputActionEvent_3 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_CareerMenuWidget.BP_CareerMenuWidget_C.InpActEvt_UIGamepadLeft_K2Node_InputActionEvent_2
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void UBP_CareerMenuWidget_C::InpActEvt_UIGamepadLeft_K2Node_InputActionEvent_2(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CareerMenuWidget_C", "InpActEvt_UIGamepadLeft_K2Node_InputActionEvent_2");

	Params::BP_CareerMenuWidget_C_InpActEvt_UIGamepadLeft_K2Node_InputActionEvent_2 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_CareerMenuWidget.BP_CareerMenuWidget_C.InpActEvt_UIGamepadRight_K2Node_InputActionEvent_4
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void UBP_CareerMenuWidget_C::InpActEvt_UIGamepadRight_K2Node_InputActionEvent_4(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CareerMenuWidget_C", "InpActEvt_UIGamepadRight_K2Node_InputActionEvent_4");

	Params::BP_CareerMenuWidget_C_InpActEvt_UIGamepadRight_K2Node_InputActionEvent_4 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_CareerMenuWidget.BP_CareerMenuWidget_C.InpActEvt_UIGamepadUp_K2Node_InputActionEvent_0
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void UBP_CareerMenuWidget_C::InpActEvt_UIGamepadUp_K2Node_InputActionEvent_0(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CareerMenuWidget_C", "InpActEvt_UIGamepadUp_K2Node_InputActionEvent_0");

	Params::BP_CareerMenuWidget_C_InpActEvt_UIGamepadUp_K2Node_InputActionEvent_0 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_CareerMenuWidget.BP_CareerMenuWidget_C.OnOpened
// (BlueprintCallable, BlueprintEvent)

void UBP_CareerMenuWidget_C::OnOpened()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CareerMenuWidget_C", "OnOpened");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CareerMenuWidget.BP_CareerMenuWidget_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_CareerMenuWidget_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CareerMenuWidget_C", "PreConstruct");

	Params::BP_CareerMenuWidget_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_CareerMenuWidget.BP_CareerMenuWidget_C.SetTotalProgress
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UBP_CareerMenuWidget_C::SetTotalProgress()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CareerMenuWidget_C", "SetTotalProgress");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CareerMenuWidget.BP_CareerMenuWidget_C.SetupHighlightableWidgets
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UBP_CareerMenuWidget_C::SetupHighlightableWidgets()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CareerMenuWidget_C", "SetupHighlightableWidgets");

	UObject::ProcessEvent(Func, nullptr);
}

}

