#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_EditorCategoryRow

#include "Basic.hpp"

#include "GYMGAME_structs.hpp"


namespace SDK::Params
{

// Function BP_EditorCategoryRow.BP_EditorCategoryRow_C.ExecuteUbergraph_BP_EditorCategoryRow
// 0x00E0 (0x00E0 - 0x0000)
struct BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGymCategoryInfo                       CallFunc_Array_Get_Item;                           // 0x0008(0x0030)()
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x003C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_ByteByte_ReturnValue;            // 0x003D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_1;        // 0x003E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_ByteByte_ReturnValue_1;          // 0x003F(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_2;        // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0041(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_3;        // 0x0042(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x0043(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetChildrenCount_ReturnValue;             // 0x0044(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0049(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x004A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4B[0x1];                                       // 0x004B(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_GetChildIndex_ReturnValue;                // 0x004C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0050(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x0054(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Percent_IntInt_ReturnValue;               // 0x0058(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_2;                 // 0x005C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWidget*                                CallFunc_GetChildAt_ReturnValue;                   // 0x0060(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Percent_IntInt_ReturnValue_1;             // 0x0068(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_6C[0x4];                                       // 0x006C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UBP_GymEditorCategorySlot_C*            K2Node_DynamicCast_AsBP_Gym_Editor_Category_Slot;  // 0x0070(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0078(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_79[0x7];                                       // 0x0079(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                CallFunc_GetChildAt_ReturnValue_1;                 // 0x0080(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UBP_GymEditorCategorySlot_C*            K2Node_DynamicCast_AsBP_Gym_Editor_Category_Slot_1; // 0x0088(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0090(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_91[0x3];                                       // 0x0091(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0094(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0098(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_99[0x3];                                       // 0x0099(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_3;                 // 0x009C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_ShouldShowDev_Show_Dev_Assets;            // 0x00A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_4;        // 0x00A1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue_1;                 // 0x00A2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue_1;                  // 0x00A3(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_5;        // 0x00A4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue_2;                  // 0x00A5(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue_3;                  // 0x00A6(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A7[0x1];                                       // 0x00A7(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	class UGymCloudApi*                           CallFunc_GetGameInstanceSubsystem_ReturnValue;     // 0x00A8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_3;                    // 0x00B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue_2;                 // 0x00B1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue_4;                  // 0x00B2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_4;                    // 0x00B3(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsClientAdmin_ReturnValue;                // 0x00B4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_RunningInPIE_ReturnValue;                 // 0x00B5(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_5;                    // 0x00B6(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_B7[0x1];                                       // 0x00B7(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	class UBP_GymEditorCategorySlot_C*            CallFunc_SpawnObject_ReturnValue;                  // 0x00B8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UPanelSlot*                             CallFunc_AddChild_ReturnValue;                     // 0x00C0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_6;                    // 0x00C8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_7;                    // 0x00C9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_CA[0x6];                                       // 0x00CA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class AGymPlayerState*                        CallFunc_GetGymPlayerState_ReturnValue;            // 0x00D0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsMapOwner_ReturnValue;                   // 0x00D8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_8;                    // 0x00D9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue_5;                  // 0x00DA(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue_6;                  // 0x00DB(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue_7;                  // 0x00DC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow) == 0x000008, "Wrong alignment on BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow");
static_assert(sizeof(BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow) == 0x0000E0, "Wrong size on BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow");
static_assert(offsetof(BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow, EntryPoint) == 0x000000, "Member 'BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow, Temp_int_Array_Index_Variable) == 0x000004, "Member 'BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow, CallFunc_Array_Get_Item) == 0x000008, "Member 'BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow, CallFunc_Array_Length_ReturnValue) == 0x000038, "Member 'BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x00003C, "Member 'BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow, CallFunc_NotEqual_ByteByte_ReturnValue) == 0x00003D, "Member 'BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow::CallFunc_NotEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow, CallFunc_EqualEqual_ByteByte_ReturnValue_1) == 0x00003E, "Member 'BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow::CallFunc_EqualEqual_ByteByte_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow, CallFunc_NotEqual_ByteByte_ReturnValue_1) == 0x00003F, "Member 'BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow::CallFunc_NotEqual_ByteByte_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow, CallFunc_EqualEqual_ByteByte_ReturnValue_2) == 0x000040, "Member 'BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow::CallFunc_EqualEqual_ByteByte_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow, CallFunc_BooleanAND_ReturnValue) == 0x000041, "Member 'BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow, CallFunc_EqualEqual_ByteByte_ReturnValue_3) == 0x000042, "Member 'BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow::CallFunc_EqualEqual_ByteByte_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow, CallFunc_BooleanOR_ReturnValue) == 0x000043, "Member 'BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow, CallFunc_GetChildrenCount_ReturnValue) == 0x000044, "Member 'BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow::CallFunc_GetChildrenCount_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow, CallFunc_IsValid_ReturnValue) == 0x000048, "Member 'BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow, CallFunc_IsValid_ReturnValue_1) == 0x000049, "Member 'BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow, CallFunc_IsValid_ReturnValue_2) == 0x00004A, "Member 'BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow, CallFunc_GetChildIndex_ReturnValue) == 0x00004C, "Member 'BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow::CallFunc_GetChildIndex_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow, CallFunc_Add_IntInt_ReturnValue) == 0x000050, "Member 'BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow, CallFunc_Add_IntInt_ReturnValue_1) == 0x000054, "Member 'BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow, CallFunc_Percent_IntInt_ReturnValue) == 0x000058, "Member 'BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow::CallFunc_Percent_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow, CallFunc_Add_IntInt_ReturnValue_2) == 0x00005C, "Member 'BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow::CallFunc_Add_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow, CallFunc_GetChildAt_ReturnValue) == 0x000060, "Member 'BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow::CallFunc_GetChildAt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow, CallFunc_Percent_IntInt_ReturnValue_1) == 0x000068, "Member 'BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow::CallFunc_Percent_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow, K2Node_DynamicCast_AsBP_Gym_Editor_Category_Slot) == 0x000070, "Member 'BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow::K2Node_DynamicCast_AsBP_Gym_Editor_Category_Slot' has a wrong offset!");
static_assert(offsetof(BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow, K2Node_DynamicCast_bSuccess) == 0x000078, "Member 'BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow, CallFunc_GetChildAt_ReturnValue_1) == 0x000080, "Member 'BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow::CallFunc_GetChildAt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow, K2Node_DynamicCast_AsBP_Gym_Editor_Category_Slot_1) == 0x000088, "Member 'BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow::K2Node_DynamicCast_AsBP_Gym_Editor_Category_Slot_1' has a wrong offset!");
static_assert(offsetof(BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow, K2Node_DynamicCast_bSuccess_1) == 0x000090, "Member 'BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow, Temp_int_Loop_Counter_Variable) == 0x000094, "Member 'BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow, CallFunc_Less_IntInt_ReturnValue) == 0x000098, "Member 'BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow, CallFunc_Add_IntInt_ReturnValue_3) == 0x00009C, "Member 'BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow::CallFunc_Add_IntInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow, CallFunc_ShouldShowDev_Show_Dev_Assets) == 0x0000A0, "Member 'BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow::CallFunc_ShouldShowDev_Show_Dev_Assets' has a wrong offset!");
static_assert(offsetof(BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow, CallFunc_EqualEqual_ByteByte_ReturnValue_4) == 0x0000A1, "Member 'BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow::CallFunc_EqualEqual_ByteByte_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow, CallFunc_BooleanAND_ReturnValue_1) == 0x0000A2, "Member 'BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow::CallFunc_BooleanAND_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow, CallFunc_BooleanOR_ReturnValue_1) == 0x0000A3, "Member 'BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow::CallFunc_BooleanOR_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow, CallFunc_EqualEqual_ByteByte_ReturnValue_5) == 0x0000A4, "Member 'BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow::CallFunc_EqualEqual_ByteByte_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow, CallFunc_BooleanOR_ReturnValue_2) == 0x0000A5, "Member 'BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow::CallFunc_BooleanOR_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow, CallFunc_BooleanOR_ReturnValue_3) == 0x0000A6, "Member 'BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow::CallFunc_BooleanOR_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow, CallFunc_GetGameInstanceSubsystem_ReturnValue) == 0x0000A8, "Member 'BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow::CallFunc_GetGameInstanceSubsystem_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow, CallFunc_IsValid_ReturnValue_3) == 0x0000B0, "Member 'BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow::CallFunc_IsValid_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow, CallFunc_BooleanAND_ReturnValue_2) == 0x0000B1, "Member 'BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow::CallFunc_BooleanAND_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow, CallFunc_BooleanOR_ReturnValue_4) == 0x0000B2, "Member 'BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow::CallFunc_BooleanOR_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow, CallFunc_IsValid_ReturnValue_4) == 0x0000B3, "Member 'BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow::CallFunc_IsValid_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow, CallFunc_IsClientAdmin_ReturnValue) == 0x0000B4, "Member 'BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow::CallFunc_IsClientAdmin_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow, CallFunc_RunningInPIE_ReturnValue) == 0x0000B5, "Member 'BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow::CallFunc_RunningInPIE_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow, CallFunc_IsValid_ReturnValue_5) == 0x0000B6, "Member 'BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow::CallFunc_IsValid_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow, CallFunc_SpawnObject_ReturnValue) == 0x0000B8, "Member 'BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow::CallFunc_SpawnObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow, CallFunc_AddChild_ReturnValue) == 0x0000C0, "Member 'BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow::CallFunc_AddChild_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow, CallFunc_IsValid_ReturnValue_6) == 0x0000C8, "Member 'BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow::CallFunc_IsValid_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow, CallFunc_IsValid_ReturnValue_7) == 0x0000C9, "Member 'BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow::CallFunc_IsValid_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow, CallFunc_GetGymPlayerState_ReturnValue) == 0x0000D0, "Member 'BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow::CallFunc_GetGymPlayerState_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow, CallFunc_IsMapOwner_ReturnValue) == 0x0000D8, "Member 'BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow::CallFunc_IsMapOwner_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow, CallFunc_IsValid_ReturnValue_8) == 0x0000D9, "Member 'BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow::CallFunc_IsValid_ReturnValue_8' has a wrong offset!");
static_assert(offsetof(BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow, CallFunc_BooleanOR_ReturnValue_5) == 0x0000DA, "Member 'BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow::CallFunc_BooleanOR_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow, CallFunc_BooleanOR_ReturnValue_6) == 0x0000DB, "Member 'BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow::CallFunc_BooleanOR_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow, CallFunc_BooleanOR_ReturnValue_7) == 0x0000DC, "Member 'BP_EditorCategoryRow_C_ExecuteUbergraph_BP_EditorCategoryRow::CallFunc_BooleanOR_ReturnValue_7' has a wrong offset!");

// Function BP_EditorCategoryRow.BP_EditorCategoryRow_C.ShouldShowDev
// 0x0030 (0x0030 - 0x0000)
struct BP_EditorCategoryRow_C_ShouldShowDev final
{
public:
	bool                                          Show_Dev_Assets;                                   // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APawn*                                  CallFunc_GetOwningPlayerPawn_ReturnValue;          // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AGymCharacter*                          K2Node_DynamicCast_AsGym_Character;                // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UGymEditorControl*                      CallFunc_GetComponentByClass_ReturnValue;          // 0x0020(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetShowDevAssets_ReturnValue;             // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0029(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_EditorCategoryRow_C_ShouldShowDev) == 0x000008, "Wrong alignment on BP_EditorCategoryRow_C_ShouldShowDev");
static_assert(sizeof(BP_EditorCategoryRow_C_ShouldShowDev) == 0x000030, "Wrong size on BP_EditorCategoryRow_C_ShouldShowDev");
static_assert(offsetof(BP_EditorCategoryRow_C_ShouldShowDev, Show_Dev_Assets) == 0x000000, "Member 'BP_EditorCategoryRow_C_ShouldShowDev::Show_Dev_Assets' has a wrong offset!");
static_assert(offsetof(BP_EditorCategoryRow_C_ShouldShowDev, CallFunc_GetOwningPlayerPawn_ReturnValue) == 0x000008, "Member 'BP_EditorCategoryRow_C_ShouldShowDev::CallFunc_GetOwningPlayerPawn_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_EditorCategoryRow_C_ShouldShowDev, K2Node_DynamicCast_AsGym_Character) == 0x000010, "Member 'BP_EditorCategoryRow_C_ShouldShowDev::K2Node_DynamicCast_AsGym_Character' has a wrong offset!");
static_assert(offsetof(BP_EditorCategoryRow_C_ShouldShowDev, K2Node_DynamicCast_bSuccess) == 0x000018, "Member 'BP_EditorCategoryRow_C_ShouldShowDev::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_EditorCategoryRow_C_ShouldShowDev, CallFunc_GetComponentByClass_ReturnValue) == 0x000020, "Member 'BP_EditorCategoryRow_C_ShouldShowDev::CallFunc_GetComponentByClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_EditorCategoryRow_C_ShouldShowDev, CallFunc_GetShowDevAssets_ReturnValue) == 0x000028, "Member 'BP_EditorCategoryRow_C_ShouldShowDev::CallFunc_GetShowDevAssets_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_EditorCategoryRow_C_ShouldShowDev, CallFunc_IsValid_ReturnValue) == 0x000029, "Member 'BP_EditorCategoryRow_C_ShouldShowDev::CallFunc_IsValid_ReturnValue' has a wrong offset!");

}

