#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_EditorGizmo

#include "Basic.hpp"

#include "GYMGAME_structs.hpp"


namespace SDK::Params
{

// Function BP_EditorGizmo.BP_EditorGizmo_C.EnableAxis
// 0x0002 (0x0002 - 0x0000)
struct BP_EditorGizmo_C_EnableAxis final
{
public:
	ERotationAxis                                 RotationAxis;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_EditorGizmo_C_EnableAxis) == 0x000001, "Wrong alignment on BP_EditorGizmo_C_EnableAxis");
static_assert(sizeof(BP_EditorGizmo_C_EnableAxis) == 0x000002, "Wrong size on BP_EditorGizmo_C_EnableAxis");
static_assert(offsetof(BP_EditorGizmo_C_EnableAxis, RotationAxis) == 0x000000, "Member 'BP_EditorGizmo_C_EnableAxis::RotationAxis' has a wrong offset!");
static_assert(offsetof(BP_EditorGizmo_C_EnableAxis, K2Node_SwitchEnum_CmpSuccess) == 0x000001, "Member 'BP_EditorGizmo_C_EnableAxis::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");

}

