#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_GymEditorWidget

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "SlateCore_structs.hpp"
#include "Slate_structs.hpp"
#include "GYMGAME_structs.hpp"
#include "UMG_structs.hpp"


namespace SDK::Params
{

// Function BP_GymEditorWidget.BP_GymEditorWidget_C.AvailableToolsCheck
// 0x0068 (0x0068 - 0x0000)
struct BP_GymEditorWidget_C_AvailableToolsCheck final
{
public:
	class AGymMap*                                CallFunc_GetActorOfClass_ReturnValue;              // 0x0000(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGymLevelKit                           CallFunc_GetLevelKit_ReturnValue;                  // 0x0010(0x0050)()
	bool                                          CallFunc_Array_Contains_ReturnValue;               // 0x0060(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_GymEditorWidget_C_AvailableToolsCheck) == 0x000008, "Wrong alignment on BP_GymEditorWidget_C_AvailableToolsCheck");
static_assert(sizeof(BP_GymEditorWidget_C_AvailableToolsCheck) == 0x000068, "Wrong size on BP_GymEditorWidget_C_AvailableToolsCheck");
static_assert(offsetof(BP_GymEditorWidget_C_AvailableToolsCheck, CallFunc_GetActorOfClass_ReturnValue) == 0x000000, "Member 'BP_GymEditorWidget_C_AvailableToolsCheck::CallFunc_GetActorOfClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_AvailableToolsCheck, CallFunc_IsValid_ReturnValue) == 0x000008, "Member 'BP_GymEditorWidget_C_AvailableToolsCheck::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_AvailableToolsCheck, CallFunc_GetLevelKit_ReturnValue) == 0x000010, "Member 'BP_GymEditorWidget_C_AvailableToolsCheck::CallFunc_GetLevelKit_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_AvailableToolsCheck, CallFunc_Array_Contains_ReturnValue) == 0x000060, "Member 'BP_GymEditorWidget_C_AvailableToolsCheck::CallFunc_Array_Contains_ReturnValue' has a wrong offset!");

// Function BP_GymEditorWidget.BP_GymEditorWidget_C.CreateCategoryPanel
// 0x0050 (0x0050 - 0x0000)
struct BP_GymEditorWidget_C_CreateCategoryPanel final
{
public:
	class UBP_EditorCategoryRow_C*                CallFunc_SpawnObject_ReturnValue;                  // 0x0000(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FMargin                                K2Node_MakeStruct_Margin;                          // 0x0008(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FAnchors                               K2Node_MakeStruct_Anchors;                         // 0x0018(0x0020)(NoDestructor)
	class UPanelSlot*                             CallFunc_AddChild_ReturnValue;                     // 0x0038(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UCanvasPanelSlot*                       K2Node_DynamicCast_AsCanvas_Panel_Slot;            // 0x0040(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_GymEditorWidget_C_CreateCategoryPanel) == 0x000008, "Wrong alignment on BP_GymEditorWidget_C_CreateCategoryPanel");
static_assert(sizeof(BP_GymEditorWidget_C_CreateCategoryPanel) == 0x000050, "Wrong size on BP_GymEditorWidget_C_CreateCategoryPanel");
static_assert(offsetof(BP_GymEditorWidget_C_CreateCategoryPanel, CallFunc_SpawnObject_ReturnValue) == 0x000000, "Member 'BP_GymEditorWidget_C_CreateCategoryPanel::CallFunc_SpawnObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_CreateCategoryPanel, K2Node_MakeStruct_Margin) == 0x000008, "Member 'BP_GymEditorWidget_C_CreateCategoryPanel::K2Node_MakeStruct_Margin' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_CreateCategoryPanel, K2Node_MakeStruct_Anchors) == 0x000018, "Member 'BP_GymEditorWidget_C_CreateCategoryPanel::K2Node_MakeStruct_Anchors' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_CreateCategoryPanel, CallFunc_AddChild_ReturnValue) == 0x000038, "Member 'BP_GymEditorWidget_C_CreateCategoryPanel::CallFunc_AddChild_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_CreateCategoryPanel, K2Node_DynamicCast_AsCanvas_Panel_Slot) == 0x000040, "Member 'BP_GymEditorWidget_C_CreateCategoryPanel::K2Node_DynamicCast_AsCanvas_Panel_Slot' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_CreateCategoryPanel, K2Node_DynamicCast_bSuccess) == 0x000048, "Member 'BP_GymEditorWidget_C_CreateCategoryPanel::K2Node_DynamicCast_bSuccess' has a wrong offset!");

// Function BP_GymEditorWidget.BP_GymEditorWidget_C.EditAssetProperty
// 0x0020 (0x0020 - 0x0000)
struct BP_GymEditorWidget_C_EditAssetProperty final
{
public:
	class AGymStaticLevelAsset*                   Asset;                                             // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FText                                   AssetName;                                         // 0x0008(0x0018)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(BP_GymEditorWidget_C_EditAssetProperty) == 0x000008, "Wrong alignment on BP_GymEditorWidget_C_EditAssetProperty");
static_assert(sizeof(BP_GymEditorWidget_C_EditAssetProperty) == 0x000020, "Wrong size on BP_GymEditorWidget_C_EditAssetProperty");
static_assert(offsetof(BP_GymEditorWidget_C_EditAssetProperty, Asset) == 0x000000, "Member 'BP_GymEditorWidget_C_EditAssetProperty::Asset' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_EditAssetProperty, AssetName) == 0x000008, "Member 'BP_GymEditorWidget_C_EditAssetProperty::AssetName' has a wrong offset!");

// Function BP_GymEditorWidget.BP_GymEditorWidget_C.ExecuteUbergraph_BP_GymEditorWidget
// 0x01A8 (0x01A8 - 0x0000)
struct BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_GetLevelKitText_ReturnValue;              // 0x0008(0x0018)()
	TArray<class UGymLevelAssetData*>             CallFunc_GetCategoryAssetEntries_ReturnValue;      // 0x0020(0x0010)(ReferenceParm)
	class UBP_EditorAssetRow_C*                   K2Node_DynamicCast_AsBP_Editor_Asset_Row;          // 0x0030(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasAnyChildren_ReturnValue;               // 0x0039(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3A[0x6];                                       // 0x003A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UBP_EditorCategoryRow_C*                K2Node_DynamicCast_AsBP_Editor_Category_Row;       // 0x0040(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsMovingAsset_ReturnValue;                // 0x0049(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_CustomEvent_InVisibility;                   // 0x004A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x004B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4C[0x4];                                       // 0x004C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                CallFunc_GetCurrentFocusedWidget_ReturnValue;      // 0x0050(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0058(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_59[0x7];                                       // 0x0059(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UBP_GymEditorCategorySlot_C*            K2Node_DynamicCast_AsBP_Gym_Editor_Category_Slot;  // 0x0060(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x0068(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_69[0x7];                                       // 0x0069(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UBP_EditorVariantSlot_C*                K2Node_DynamicCast_AsBP_Editor_Variant_Slot;       // 0x0070(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_3;                     // 0x0078(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_79[0x7];                                       // 0x0079(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UBP_EditorOptionSlot_C*                 K2Node_DynamicCast_AsBP_Editor_Option_Slot;        // 0x0080(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_4;                     // 0x0088(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_89[0x7];                                       // 0x0089(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UBP_EditorAssetSlot_C*                  K2Node_DynamicCast_AsBP_Editor_Asset_Slot;         // 0x0090(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_5;                     // 0x0098(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_99[0x7];                                       // 0x0099(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UBP_EditorPiece_C*                      K2Node_DynamicCast_AsBP_Editor_Piece;              // 0x00A0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_6;                     // 0x00A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A9[0x7];                                       // 0x00A9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_GymMap_C*                           CallFunc_GetActorOfClass_ReturnValue;              // 0x00B0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UWBP_AssetPropertyEditorWidget_C*       K2Node_DynamicCast_AsWBP_Asset_Property_Editor_Widget; // 0x00B8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_7;                     // 0x00C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C1[0x7];                                       // 0x00C1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AGymStaticLevelAsset*                   K2Node_Event_Asset_1;                              // 0x00C8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FText                                   K2Node_Event_AssetName;                            // 0x00D0(0x0018)(ConstParm)
	class UWBP_AssetPropertyEditorWidget_C*       K2Node_DynamicCast_AsWBP_Asset_Property_Editor_Widget_1; // 0x00E8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_8;                     // 0x00F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EditorIsOpen_ReturnValue;                 // 0x00F1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EGymEditorCategory                            K2Node_Event_Category;                             // 0x00F2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_F3[0x1];                                       // 0x00F3(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGymAssetVariantId                     K2Node_Event_VariantId;                            // 0x00F4(0x0010)(NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_104[0x4];                                      // 0x0104(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AGymStaticLevelAsset*                   K2Node_Event_Asset;                                // 0x0108(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UBP_EditorAssetRow_C*                   K2Node_DynamicCast_AsBP_Editor_Asset_Row_1;        // 0x0110(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_9;                     // 0x0118(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0119(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_11A[0x6];                                      // 0x011A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UBP_EditorAssetSlot_C*                  CallFunc_Get_Asset_Slot_for_Asset_AssetSlot;       // 0x0120(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UBP_EditorVariantSlot_C*                CallFunc_Get_Asset_Slot_for_Asset_VariantSlot;     // 0x0128(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UGymLevelAssetData*                     CallFunc_Get_Asset_Slot_for_Asset_AssetObject;     // 0x0130(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Get_Asset_Slot_for_Asset_VariantIndex;    // 0x0138(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Get_Asset_Slot_for_Asset_Success;         // 0x013C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_13D[0x3];                                      // 0x013D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_AssetPropertyEditorWidget_C*       K2Node_DynamicCast_AsWBP_Asset_Property_Editor_Widget_2; // 0x0140(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_10;                    // 0x0148(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EditorIsOpen_ReturnValue_1;               // 0x0149(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_14A[0x6];                                      // 0x014A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_AssetPropertyEditorWidget_C*       K2Node_DynamicCast_AsWBP_Asset_Property_Editor_Widget_3; // 0x0150(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_11;                    // 0x0158(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue;      // 0x0159(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x015A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_3;                    // 0x015B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_4;                    // 0x015C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_5;                    // 0x015D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_6;                    // 0x015E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_7;                    // 0x015F(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_8;                    // 0x0160(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_161[0x3];                                      // 0x0161(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(ESlateVisibility InVisibility)> K2Node_CreateDelegate_OutputDelegate;              // 0x0164(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasAnyUserFocus_ReturnValue;              // 0x0174(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0175(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_176[0x2];                                      // 0x0176(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class UGymSaveGameTutorial*                   CallFunc_GetSaveFile_ReturnValue;                  // 0x0178(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_9;                    // 0x0180(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_181[0x3];                                      // 0x0181(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_GetRewardsClaimed_ReturnValue;            // 0x0184(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x0188(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bIsMovingAsset;                       // 0x0189(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_18A[0x6];                                      // 0x018A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_GetLevelKitText_ReturnValue_1;            // 0x0190(0x0018)()
};
static_assert(alignof(BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget) == 0x000008, "Wrong alignment on BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget");
static_assert(sizeof(BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget) == 0x0001A8, "Wrong size on BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget");
static_assert(offsetof(BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget, EntryPoint) == 0x000000, "Member 'BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget, CallFunc_GetLevelKitText_ReturnValue) == 0x000008, "Member 'BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget::CallFunc_GetLevelKitText_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget, CallFunc_GetCategoryAssetEntries_ReturnValue) == 0x000020, "Member 'BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget::CallFunc_GetCategoryAssetEntries_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget, K2Node_DynamicCast_AsBP_Editor_Asset_Row) == 0x000030, "Member 'BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget::K2Node_DynamicCast_AsBP_Editor_Asset_Row' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget, K2Node_DynamicCast_bSuccess) == 0x000038, "Member 'BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget, CallFunc_HasAnyChildren_ReturnValue) == 0x000039, "Member 'BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget::CallFunc_HasAnyChildren_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget, K2Node_DynamicCast_AsBP_Editor_Category_Row) == 0x000040, "Member 'BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget::K2Node_DynamicCast_AsBP_Editor_Category_Row' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget, K2Node_DynamicCast_bSuccess_1) == 0x000048, "Member 'BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget, CallFunc_IsMovingAsset_ReturnValue) == 0x000049, "Member 'BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget::CallFunc_IsMovingAsset_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget, K2Node_CustomEvent_InVisibility) == 0x00004A, "Member 'BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget::K2Node_CustomEvent_InVisibility' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget, K2Node_SwitchEnum_CmpSuccess) == 0x00004B, "Member 'BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget, CallFunc_GetCurrentFocusedWidget_ReturnValue) == 0x000050, "Member 'BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget::CallFunc_GetCurrentFocusedWidget_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget, CallFunc_IsValid_ReturnValue) == 0x000058, "Member 'BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget, K2Node_DynamicCast_AsBP_Gym_Editor_Category_Slot) == 0x000060, "Member 'BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget::K2Node_DynamicCast_AsBP_Gym_Editor_Category_Slot' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget, K2Node_DynamicCast_bSuccess_2) == 0x000068, "Member 'BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget, K2Node_DynamicCast_AsBP_Editor_Variant_Slot) == 0x000070, "Member 'BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget::K2Node_DynamicCast_AsBP_Editor_Variant_Slot' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget, K2Node_DynamicCast_bSuccess_3) == 0x000078, "Member 'BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget::K2Node_DynamicCast_bSuccess_3' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget, K2Node_DynamicCast_AsBP_Editor_Option_Slot) == 0x000080, "Member 'BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget::K2Node_DynamicCast_AsBP_Editor_Option_Slot' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget, K2Node_DynamicCast_bSuccess_4) == 0x000088, "Member 'BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget::K2Node_DynamicCast_bSuccess_4' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget, K2Node_DynamicCast_AsBP_Editor_Asset_Slot) == 0x000090, "Member 'BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget::K2Node_DynamicCast_AsBP_Editor_Asset_Slot' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget, K2Node_DynamicCast_bSuccess_5) == 0x000098, "Member 'BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget::K2Node_DynamicCast_bSuccess_5' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget, K2Node_DynamicCast_AsBP_Editor_Piece) == 0x0000A0, "Member 'BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget::K2Node_DynamicCast_AsBP_Editor_Piece' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget, K2Node_DynamicCast_bSuccess_6) == 0x0000A8, "Member 'BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget::K2Node_DynamicCast_bSuccess_6' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget, CallFunc_GetActorOfClass_ReturnValue) == 0x0000B0, "Member 'BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget::CallFunc_GetActorOfClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget, K2Node_DynamicCast_AsWBP_Asset_Property_Editor_Widget) == 0x0000B8, "Member 'BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget::K2Node_DynamicCast_AsWBP_Asset_Property_Editor_Widget' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget, K2Node_DynamicCast_bSuccess_7) == 0x0000C0, "Member 'BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget::K2Node_DynamicCast_bSuccess_7' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget, K2Node_Event_Asset_1) == 0x0000C8, "Member 'BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget::K2Node_Event_Asset_1' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget, K2Node_Event_AssetName) == 0x0000D0, "Member 'BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget::K2Node_Event_AssetName' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget, K2Node_DynamicCast_AsWBP_Asset_Property_Editor_Widget_1) == 0x0000E8, "Member 'BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget::K2Node_DynamicCast_AsWBP_Asset_Property_Editor_Widget_1' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget, K2Node_DynamicCast_bSuccess_8) == 0x0000F0, "Member 'BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget::K2Node_DynamicCast_bSuccess_8' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget, CallFunc_EditorIsOpen_ReturnValue) == 0x0000F1, "Member 'BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget::CallFunc_EditorIsOpen_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget, K2Node_Event_Category) == 0x0000F2, "Member 'BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget::K2Node_Event_Category' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget, K2Node_Event_VariantId) == 0x0000F4, "Member 'BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget::K2Node_Event_VariantId' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget, K2Node_Event_Asset) == 0x000108, "Member 'BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget::K2Node_Event_Asset' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget, K2Node_DynamicCast_AsBP_Editor_Asset_Row_1) == 0x000110, "Member 'BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget::K2Node_DynamicCast_AsBP_Editor_Asset_Row_1' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget, K2Node_DynamicCast_bSuccess_9) == 0x000118, "Member 'BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget::K2Node_DynamicCast_bSuccess_9' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget, CallFunc_IsValid_ReturnValue_1) == 0x000119, "Member 'BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget, CallFunc_Get_Asset_Slot_for_Asset_AssetSlot) == 0x000120, "Member 'BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget::CallFunc_Get_Asset_Slot_for_Asset_AssetSlot' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget, CallFunc_Get_Asset_Slot_for_Asset_VariantSlot) == 0x000128, "Member 'BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget::CallFunc_Get_Asset_Slot_for_Asset_VariantSlot' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget, CallFunc_Get_Asset_Slot_for_Asset_AssetObject) == 0x000130, "Member 'BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget::CallFunc_Get_Asset_Slot_for_Asset_AssetObject' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget, CallFunc_Get_Asset_Slot_for_Asset_VariantIndex) == 0x000138, "Member 'BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget::CallFunc_Get_Asset_Slot_for_Asset_VariantIndex' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget, CallFunc_Get_Asset_Slot_for_Asset_Success) == 0x00013C, "Member 'BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget::CallFunc_Get_Asset_Slot_for_Asset_Success' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget, K2Node_DynamicCast_AsWBP_Asset_Property_Editor_Widget_2) == 0x000140, "Member 'BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget::K2Node_DynamicCast_AsWBP_Asset_Property_Editor_Widget_2' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget, K2Node_DynamicCast_bSuccess_10) == 0x000148, "Member 'BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget::K2Node_DynamicCast_bSuccess_10' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget, CallFunc_EditorIsOpen_ReturnValue_1) == 0x000149, "Member 'BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget::CallFunc_EditorIsOpen_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget, K2Node_DynamicCast_AsWBP_Asset_Property_Editor_Widget_3) == 0x000150, "Member 'BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget::K2Node_DynamicCast_AsWBP_Asset_Property_Editor_Widget_3' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget, K2Node_DynamicCast_bSuccess_11) == 0x000158, "Member 'BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget::K2Node_DynamicCast_bSuccess_11' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget, CallFunc_EqualEqual_ObjectObject_ReturnValue) == 0x000159, "Member 'BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget::CallFunc_EqualEqual_ObjectObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget, CallFunc_IsValid_ReturnValue_2) == 0x00015A, "Member 'BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget, CallFunc_IsValid_ReturnValue_3) == 0x00015B, "Member 'BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget::CallFunc_IsValid_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget, CallFunc_IsValid_ReturnValue_4) == 0x00015C, "Member 'BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget::CallFunc_IsValid_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget, CallFunc_IsValid_ReturnValue_5) == 0x00015D, "Member 'BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget::CallFunc_IsValid_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget, CallFunc_IsValid_ReturnValue_6) == 0x00015E, "Member 'BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget::CallFunc_IsValid_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget, CallFunc_IsValid_ReturnValue_7) == 0x00015F, "Member 'BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget::CallFunc_IsValid_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget, CallFunc_IsValid_ReturnValue_8) == 0x000160, "Member 'BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget::CallFunc_IsValid_ReturnValue_8' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget, K2Node_CreateDelegate_OutputDelegate) == 0x000164, "Member 'BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget, CallFunc_HasAnyUserFocus_ReturnValue) == 0x000174, "Member 'BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget::CallFunc_HasAnyUserFocus_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget, CallFunc_Not_PreBool_ReturnValue) == 0x000175, "Member 'BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget, CallFunc_GetSaveFile_ReturnValue) == 0x000178, "Member 'BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget::CallFunc_GetSaveFile_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget, CallFunc_IsValid_ReturnValue_9) == 0x000180, "Member 'BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget::CallFunc_IsValid_ReturnValue_9' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget, CallFunc_GetRewardsClaimed_ReturnValue) == 0x000184, "Member 'BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget::CallFunc_GetRewardsClaimed_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget, CallFunc_Greater_IntInt_ReturnValue) == 0x000188, "Member 'BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget::CallFunc_Greater_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget, K2Node_Event_bIsMovingAsset) == 0x000189, "Member 'BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget::K2Node_Event_bIsMovingAsset' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget, CallFunc_GetLevelKitText_ReturnValue_1) == 0x000190, "Member 'BP_GymEditorWidget_C_ExecuteUbergraph_BP_GymEditorWidget::CallFunc_GetLevelKitText_ReturnValue_1' has a wrong offset!");

// Function BP_GymEditorWidget.BP_GymEditorWidget_C.GetBrush_0
// 0x0540 (0x0540 - 0x0000)
struct BP_GymEditorWidget_C_GetBrush_0 final
{
public:
	struct FSlateBrush                            ReturnValue;                                       // 0x0000(0x00D0)(Parm, OutParm, ReturnParm)
	struct FSlateColor                            Tint;                                              // 0x00D0(0x0014)(Edit, BlueprintVisible)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x00E4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_E5[0x3];                                       // 0x00E5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector2D                              CallFunc_MakeVector2D_ReturnValue;                 // 0x00E8(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_F8[0x8];                                       // 0x00F8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSlateBrush                            K2Node_MakeStruct_SlateBrush;                      // 0x0100(0x00D0)()
	struct FSlateBrush                            K2Node_MakeStruct_SlateBrush_1;                    // 0x01D0(0x00D0)()
	struct FSlateBrush                            K2Node_MakeStruct_SlateBrush_2;                    // 0x02A0(0x00D0)()
	struct FSlateBrush                            K2Node_MakeStruct_SlateBrush_3;                    // 0x0370(0x00D0)()
	struct FSlateBrush                            K2Node_MakeStruct_SlateBrush_4;                    // 0x0440(0x00D0)()
	struct FDeprecateSlateVector2D                K2Node_MakeStruct_ImageSize_ImplicitCast;          // 0x0510(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FDeprecateSlateVector2D                K2Node_MakeStruct_ImageSize_ImplicitCast_1;        // 0x0518(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FDeprecateSlateVector2D                K2Node_MakeStruct_ImageSize_ImplicitCast_2;        // 0x0520(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FDeprecateSlateVector2D                K2Node_MakeStruct_ImageSize_ImplicitCast_3;        // 0x0528(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FDeprecateSlateVector2D                K2Node_MakeStruct_ImageSize_ImplicitCast_4;        // 0x0530(0x0008)(NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_GymEditorWidget_C_GetBrush_0) == 0x000010, "Wrong alignment on BP_GymEditorWidget_C_GetBrush_0");
static_assert(sizeof(BP_GymEditorWidget_C_GetBrush_0) == 0x000540, "Wrong size on BP_GymEditorWidget_C_GetBrush_0");
static_assert(offsetof(BP_GymEditorWidget_C_GetBrush_0, ReturnValue) == 0x000000, "Member 'BP_GymEditorWidget_C_GetBrush_0::ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_GetBrush_0, Tint) == 0x0000D0, "Member 'BP_GymEditorWidget_C_GetBrush_0::Tint' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_GetBrush_0, K2Node_SwitchEnum_CmpSuccess) == 0x0000E4, "Member 'BP_GymEditorWidget_C_GetBrush_0::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_GetBrush_0, CallFunc_MakeVector2D_ReturnValue) == 0x0000E8, "Member 'BP_GymEditorWidget_C_GetBrush_0::CallFunc_MakeVector2D_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_GetBrush_0, K2Node_MakeStruct_SlateBrush) == 0x000100, "Member 'BP_GymEditorWidget_C_GetBrush_0::K2Node_MakeStruct_SlateBrush' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_GetBrush_0, K2Node_MakeStruct_SlateBrush_1) == 0x0001D0, "Member 'BP_GymEditorWidget_C_GetBrush_0::K2Node_MakeStruct_SlateBrush_1' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_GetBrush_0, K2Node_MakeStruct_SlateBrush_2) == 0x0002A0, "Member 'BP_GymEditorWidget_C_GetBrush_0::K2Node_MakeStruct_SlateBrush_2' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_GetBrush_0, K2Node_MakeStruct_SlateBrush_3) == 0x000370, "Member 'BP_GymEditorWidget_C_GetBrush_0::K2Node_MakeStruct_SlateBrush_3' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_GetBrush_0, K2Node_MakeStruct_SlateBrush_4) == 0x000440, "Member 'BP_GymEditorWidget_C_GetBrush_0::K2Node_MakeStruct_SlateBrush_4' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_GetBrush_0, K2Node_MakeStruct_ImageSize_ImplicitCast) == 0x000510, "Member 'BP_GymEditorWidget_C_GetBrush_0::K2Node_MakeStruct_ImageSize_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_GetBrush_0, K2Node_MakeStruct_ImageSize_ImplicitCast_1) == 0x000518, "Member 'BP_GymEditorWidget_C_GetBrush_0::K2Node_MakeStruct_ImageSize_ImplicitCast_1' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_GetBrush_0, K2Node_MakeStruct_ImageSize_ImplicitCast_2) == 0x000520, "Member 'BP_GymEditorWidget_C_GetBrush_0::K2Node_MakeStruct_ImageSize_ImplicitCast_2' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_GetBrush_0, K2Node_MakeStruct_ImageSize_ImplicitCast_3) == 0x000528, "Member 'BP_GymEditorWidget_C_GetBrush_0::K2Node_MakeStruct_ImageSize_ImplicitCast_3' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_GetBrush_0, K2Node_MakeStruct_ImageSize_ImplicitCast_4) == 0x000530, "Member 'BP_GymEditorWidget_C_GetBrush_0::K2Node_MakeStruct_ImageSize_ImplicitCast_4' has a wrong offset!");

// Function BP_GymEditorWidget.BP_GymEditorWidget_C.GetLevelKitName
// 0x0020 (0x0020 - 0x0000)
struct BP_GymEditorWidget_C_GetLevelKitName final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ReturnParm)
	bool                                          CallFunc_TextIsEmpty_ReturnValue;                  // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_GymEditorWidget_C_GetLevelKitName) == 0x000008, "Wrong alignment on BP_GymEditorWidget_C_GetLevelKitName");
static_assert(sizeof(BP_GymEditorWidget_C_GetLevelKitName) == 0x000020, "Wrong size on BP_GymEditorWidget_C_GetLevelKitName");
static_assert(offsetof(BP_GymEditorWidget_C_GetLevelKitName, ReturnValue) == 0x000000, "Member 'BP_GymEditorWidget_C_GetLevelKitName::ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_GetLevelKitName, CallFunc_TextIsEmpty_ReturnValue) == 0x000018, "Member 'BP_GymEditorWidget_C_GetLevelKitName::CallFunc_TextIsEmpty_ReturnValue' has a wrong offset!");

// Function BP_GymEditorWidget.BP_GymEditorWidget_C.GetLevelKitText
// 0x0020 (0x0020 - 0x0000)
struct BP_GymEditorWidget_C_GetLevelKitText final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ReturnParm)
	bool                                          CallFunc_TextIsEmpty_ReturnValue;                  // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_GymEditorWidget_C_GetLevelKitText) == 0x000008, "Wrong alignment on BP_GymEditorWidget_C_GetLevelKitText");
static_assert(sizeof(BP_GymEditorWidget_C_GetLevelKitText) == 0x000020, "Wrong size on BP_GymEditorWidget_C_GetLevelKitText");
static_assert(offsetof(BP_GymEditorWidget_C_GetLevelKitText, ReturnValue) == 0x000000, "Member 'BP_GymEditorWidget_C_GetLevelKitText::ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_GetLevelKitText, CallFunc_TextIsEmpty_ReturnValue) == 0x000018, "Member 'BP_GymEditorWidget_C_GetLevelKitText::CallFunc_TextIsEmpty_ReturnValue' has a wrong offset!");

// Function BP_GymEditorWidget.BP_GymEditorWidget_C.GetToolFromBP
// 0x0010 (0x0010 - 0x0000)
struct BP_GymEditorWidget_C_GetToolFromBP final
{
public:
	class UGymToolSetting*                        ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash)
	class UGymBoundsToolSetting*                  CallFunc_SpawnObject_ReturnValue;                  // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_GymEditorWidget_C_GetToolFromBP) == 0x000008, "Wrong alignment on BP_GymEditorWidget_C_GetToolFromBP");
static_assert(sizeof(BP_GymEditorWidget_C_GetToolFromBP) == 0x000010, "Wrong size on BP_GymEditorWidget_C_GetToolFromBP");
static_assert(offsetof(BP_GymEditorWidget_C_GetToolFromBP, ReturnValue) == 0x000000, "Member 'BP_GymEditorWidget_C_GetToolFromBP::ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_GetToolFromBP, CallFunc_SpawnObject_ReturnValue) == 0x000008, "Member 'BP_GymEditorWidget_C_GetToolFromBP::CallFunc_SpawnObject_ReturnValue' has a wrong offset!");

// Function BP_GymEditorWidget.BP_GymEditorWidget_C.OnEditAssetPropertyVariantChanged
// 0x0020 (0x0020 - 0x0000)
struct BP_GymEditorWidget_C_OnEditAssetPropertyVariantChanged final
{
public:
	class AGymStaticLevelAsset*                   Asset;                                             // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FText                                   AssetName;                                         // 0x0008(0x0018)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(BP_GymEditorWidget_C_OnEditAssetPropertyVariantChanged) == 0x000008, "Wrong alignment on BP_GymEditorWidget_C_OnEditAssetPropertyVariantChanged");
static_assert(sizeof(BP_GymEditorWidget_C_OnEditAssetPropertyVariantChanged) == 0x000020, "Wrong size on BP_GymEditorWidget_C_OnEditAssetPropertyVariantChanged");
static_assert(offsetof(BP_GymEditorWidget_C_OnEditAssetPropertyVariantChanged, Asset) == 0x000000, "Member 'BP_GymEditorWidget_C_OnEditAssetPropertyVariantChanged::Asset' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_OnEditAssetPropertyVariantChanged, AssetName) == 0x000008, "Member 'BP_GymEditorWidget_C_OnEditAssetPropertyVariantChanged::AssetName' has a wrong offset!");

// Function BP_GymEditorWidget.BP_GymEditorWidget_C.OnMovingAssetChanged
// 0x0001 (0x0001 - 0x0000)
struct BP_GymEditorWidget_C_OnMovingAssetChanged final
{
public:
	bool                                          bIsMovingAsset;                                    // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_GymEditorWidget_C_OnMovingAssetChanged) == 0x000001, "Wrong alignment on BP_GymEditorWidget_C_OnMovingAssetChanged");
static_assert(sizeof(BP_GymEditorWidget_C_OnMovingAssetChanged) == 0x000001, "Wrong size on BP_GymEditorWidget_C_OnMovingAssetChanged");
static_assert(offsetof(BP_GymEditorWidget_C_OnMovingAssetChanged, bIsMovingAsset) == 0x000000, "Member 'BP_GymEditorWidget_C_OnMovingAssetChanged::bIsMovingAsset' has a wrong offset!");

// Function BP_GymEditorWidget.BP_GymEditorWidget_C.OnPropertiesChangedForAsset
// 0x0008 (0x0008 - 0x0000)
struct BP_GymEditorWidget_C_OnPropertiesChangedForAsset final
{
public:
	class AGymStaticLevelAsset*                   Asset;                                             // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_GymEditorWidget_C_OnPropertiesChangedForAsset) == 0x000008, "Wrong alignment on BP_GymEditorWidget_C_OnPropertiesChangedForAsset");
static_assert(sizeof(BP_GymEditorWidget_C_OnPropertiesChangedForAsset) == 0x000008, "Wrong size on BP_GymEditorWidget_C_OnPropertiesChangedForAsset");
static_assert(offsetof(BP_GymEditorWidget_C_OnPropertiesChangedForAsset, Asset) == 0x000000, "Member 'BP_GymEditorWidget_C_OnPropertiesChangedForAsset::Asset' has a wrong offset!");

// Function BP_GymEditorWidget.BP_GymEditorWidget_C.OnVisibilityChanged_Event
// 0x0001 (0x0001 - 0x0000)
struct BP_GymEditorWidget_C_OnVisibilityChanged_Event final
{
public:
	ESlateVisibility                              InVisibility;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_GymEditorWidget_C_OnVisibilityChanged_Event) == 0x000001, "Wrong alignment on BP_GymEditorWidget_C_OnVisibilityChanged_Event");
static_assert(sizeof(BP_GymEditorWidget_C_OnVisibilityChanged_Event) == 0x000001, "Wrong size on BP_GymEditorWidget_C_OnVisibilityChanged_Event");
static_assert(offsetof(BP_GymEditorWidget_C_OnVisibilityChanged_Event, InVisibility) == 0x000000, "Member 'BP_GymEditorWidget_C_OnVisibilityChanged_Event::InVisibility' has a wrong offset!");

// Function BP_GymEditorWidget.BP_GymEditorWidget_C.OpenCategoryAndVariant
// 0x0014 (0x0014 - 0x0000)
struct BP_GymEditorWidget_C_OpenCategoryAndVariant final
{
public:
	EGymEditorCategory                            Category;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGymAssetVariantId                     VariantId;                                         // 0x0004(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_GymEditorWidget_C_OpenCategoryAndVariant) == 0x000004, "Wrong alignment on BP_GymEditorWidget_C_OpenCategoryAndVariant");
static_assert(sizeof(BP_GymEditorWidget_C_OpenCategoryAndVariant) == 0x000014, "Wrong size on BP_GymEditorWidget_C_OpenCategoryAndVariant");
static_assert(offsetof(BP_GymEditorWidget_C_OpenCategoryAndVariant, Category) == 0x000000, "Member 'BP_GymEditorWidget_C_OpenCategoryAndVariant::Category' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_OpenCategoryAndVariant, VariantId) == 0x000004, "Member 'BP_GymEditorWidget_C_OpenCategoryAndVariant::VariantId' has a wrong offset!");

// Function BP_GymEditorWidget.BP_GymEditorWidget_C.SelectCategory
// 0x0200 (0x0200 - 0x0000)
struct BP_GymEditorWidget_C_SelectCategory final
{
public:
	EGymEditorCategory                            Category;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_GetEnumeratorUserFriendlyName_ReturnValue; // 0x0008(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class UBP_EditorOptionsRow_C*                 CallFunc_SpawnObject_ReturnValue;                  // 0x0018(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TArray<class UGymLevelAssetData*>             CallFunc_GetCategoryAssetEntries_ReturnValue;      // 0x0020(0x0010)(ReferenceParm)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_31[0x7];                                       // 0x0031(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue;              // 0x0038(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UBP_EditorPhysicsRow_C*                 CallFunc_SpawnObject_ReturnValue_1;                // 0x0040(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class AGymPlayerController*                   K2Node_DynamicCast_AsGym_Player_Controller;        // 0x0048(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_51[0x7];                                       // 0x0051(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue_1;            // 0x0058(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AGymPlayerController*                   K2Node_DynamicCast_AsGym_Player_Controller_1;      // 0x0060(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0068(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0069(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_6A[0x6];                                       // 0x006A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UGymGuiPauseMenu*                       CallFunc_GetPauseMenu_ReturnValue;                 // 0x0070(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0078(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x0079(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_3;                    // 0x007A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Remove_ReturnValue;                   // 0x007B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_7C[0x4];                                       // 0x007C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UBP_EditorToolsRow_C*                   CallFunc_SpawnObject_ReturnValue_2;                // 0x0080(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UWidget*                                CallFunc_Map_Find_Value;                           // 0x0088(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue;                     // 0x0090(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_91[0x7];                                       // 0x0091(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                CallFunc_Map_Find_Value_1;                         // 0x0098(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue_1;                   // 0x00A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A1[0x7];                                       // 0x00A1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UBP_EditorAssetRow_C*                   K2Node_DynamicCast_AsBP_Editor_Asset_Row;          // 0x00A8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x00B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_B1[0x7];                                       // 0x00B1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UBP_EditorAssetRow_C*                   K2Node_DynamicCast_AsBP_Editor_Asset_Row_1;        // 0x00B8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_3;                     // 0x00C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_StrStr_ReturnValue;            // 0x00C1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C2[0x6];                                       // 0x00C2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                CallFunc_Map_Find_Value_2;                         // 0x00C8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue_2;                   // 0x00D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D1[0x7];                                       // 0x00D1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAnchors                               K2Node_MakeStruct_Anchors;                         // 0x00D8(0x0020)(NoDestructor)
	class UBP_EditorAssetRow_C*                   CallFunc_SpawnObject_ReturnValue_3;                // 0x00F8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FMargin                                K2Node_MakeStruct_Margin;                          // 0x0100(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FAnchors                               K2Node_MakeStruct_Anchors_1;                       // 0x0110(0x0020)(NoDestructor)
	struct FMargin                                K2Node_MakeStruct_Margin_1;                        // 0x0130(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FAnchors                               K2Node_MakeStruct_Anchors_2;                       // 0x0140(0x0020)(NoDestructor)
	struct FMargin                                K2Node_MakeStruct_Margin_2;                        // 0x0160(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class UPanelSlot*                             CallFunc_AddChild_ReturnValue;                     // 0x0170(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UPanelSlot*                             CallFunc_AddChild_ReturnValue_1;                   // 0x0178(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UCanvasPanelSlot*                       K2Node_DynamicCast_AsCanvas_Panel_Slot;            // 0x0180(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_4;                     // 0x0188(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_189[0x7];                                      // 0x0189(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UCanvasPanelSlot*                       K2Node_DynamicCast_AsCanvas_Panel_Slot_1;          // 0x0190(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_5;                     // 0x0198(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_199[0x7];                                      // 0x0199(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UPanelSlot*                             CallFunc_AddChild_ReturnValue_2;                   // 0x01A0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UCanvasPanelSlot*                       K2Node_DynamicCast_AsCanvas_Panel_Slot_2;          // 0x01A8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_6;                     // 0x01B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1B1[0x7];                                      // 0x01B1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UPanelSlot*                             CallFunc_AddChild_ReturnValue_3;                   // 0x01B8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UCanvasPanelSlot*                       K2Node_DynamicCast_AsCanvas_Panel_Slot_3;          // 0x01C0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_7;                     // 0x01C8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1C9[0x3];                                      // 0x01C9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FMargin                                K2Node_MakeStruct_Margin_3;                        // 0x01CC(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1DC[0x4];                                      // 0x01DC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAnchors                               K2Node_MakeStruct_Anchors_3;                       // 0x01E0(0x0020)(NoDestructor)
};
static_assert(alignof(BP_GymEditorWidget_C_SelectCategory) == 0x000008, "Wrong alignment on BP_GymEditorWidget_C_SelectCategory");
static_assert(sizeof(BP_GymEditorWidget_C_SelectCategory) == 0x000200, "Wrong size on BP_GymEditorWidget_C_SelectCategory");
static_assert(offsetof(BP_GymEditorWidget_C_SelectCategory, Category) == 0x000000, "Member 'BP_GymEditorWidget_C_SelectCategory::Category' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_SelectCategory, CallFunc_GetEnumeratorUserFriendlyName_ReturnValue) == 0x000008, "Member 'BP_GymEditorWidget_C_SelectCategory::CallFunc_GetEnumeratorUserFriendlyName_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_SelectCategory, CallFunc_SpawnObject_ReturnValue) == 0x000018, "Member 'BP_GymEditorWidget_C_SelectCategory::CallFunc_SpawnObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_SelectCategory, CallFunc_GetCategoryAssetEntries_ReturnValue) == 0x000020, "Member 'BP_GymEditorWidget_C_SelectCategory::CallFunc_GetCategoryAssetEntries_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_SelectCategory, K2Node_SwitchEnum_CmpSuccess) == 0x000030, "Member 'BP_GymEditorWidget_C_SelectCategory::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_SelectCategory, CallFunc_GetOwningPlayer_ReturnValue) == 0x000038, "Member 'BP_GymEditorWidget_C_SelectCategory::CallFunc_GetOwningPlayer_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_SelectCategory, CallFunc_SpawnObject_ReturnValue_1) == 0x000040, "Member 'BP_GymEditorWidget_C_SelectCategory::CallFunc_SpawnObject_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_SelectCategory, K2Node_DynamicCast_AsGym_Player_Controller) == 0x000048, "Member 'BP_GymEditorWidget_C_SelectCategory::K2Node_DynamicCast_AsGym_Player_Controller' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_SelectCategory, K2Node_DynamicCast_bSuccess) == 0x000050, "Member 'BP_GymEditorWidget_C_SelectCategory::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_SelectCategory, CallFunc_GetOwningPlayer_ReturnValue_1) == 0x000058, "Member 'BP_GymEditorWidget_C_SelectCategory::CallFunc_GetOwningPlayer_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_SelectCategory, K2Node_DynamicCast_AsGym_Player_Controller_1) == 0x000060, "Member 'BP_GymEditorWidget_C_SelectCategory::K2Node_DynamicCast_AsGym_Player_Controller_1' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_SelectCategory, K2Node_DynamicCast_bSuccess_1) == 0x000068, "Member 'BP_GymEditorWidget_C_SelectCategory::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_SelectCategory, CallFunc_IsValid_ReturnValue) == 0x000069, "Member 'BP_GymEditorWidget_C_SelectCategory::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_SelectCategory, CallFunc_GetPauseMenu_ReturnValue) == 0x000070, "Member 'BP_GymEditorWidget_C_SelectCategory::CallFunc_GetPauseMenu_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_SelectCategory, CallFunc_IsValid_ReturnValue_1) == 0x000078, "Member 'BP_GymEditorWidget_C_SelectCategory::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_SelectCategory, CallFunc_IsValid_ReturnValue_2) == 0x000079, "Member 'BP_GymEditorWidget_C_SelectCategory::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_SelectCategory, CallFunc_IsValid_ReturnValue_3) == 0x00007A, "Member 'BP_GymEditorWidget_C_SelectCategory::CallFunc_IsValid_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_SelectCategory, CallFunc_Map_Remove_ReturnValue) == 0x00007B, "Member 'BP_GymEditorWidget_C_SelectCategory::CallFunc_Map_Remove_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_SelectCategory, CallFunc_SpawnObject_ReturnValue_2) == 0x000080, "Member 'BP_GymEditorWidget_C_SelectCategory::CallFunc_SpawnObject_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_SelectCategory, CallFunc_Map_Find_Value) == 0x000088, "Member 'BP_GymEditorWidget_C_SelectCategory::CallFunc_Map_Find_Value' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_SelectCategory, CallFunc_Map_Find_ReturnValue) == 0x000090, "Member 'BP_GymEditorWidget_C_SelectCategory::CallFunc_Map_Find_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_SelectCategory, CallFunc_Map_Find_Value_1) == 0x000098, "Member 'BP_GymEditorWidget_C_SelectCategory::CallFunc_Map_Find_Value_1' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_SelectCategory, CallFunc_Map_Find_ReturnValue_1) == 0x0000A0, "Member 'BP_GymEditorWidget_C_SelectCategory::CallFunc_Map_Find_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_SelectCategory, K2Node_DynamicCast_AsBP_Editor_Asset_Row) == 0x0000A8, "Member 'BP_GymEditorWidget_C_SelectCategory::K2Node_DynamicCast_AsBP_Editor_Asset_Row' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_SelectCategory, K2Node_DynamicCast_bSuccess_2) == 0x0000B0, "Member 'BP_GymEditorWidget_C_SelectCategory::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_SelectCategory, K2Node_DynamicCast_AsBP_Editor_Asset_Row_1) == 0x0000B8, "Member 'BP_GymEditorWidget_C_SelectCategory::K2Node_DynamicCast_AsBP_Editor_Asset_Row_1' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_SelectCategory, K2Node_DynamicCast_bSuccess_3) == 0x0000C0, "Member 'BP_GymEditorWidget_C_SelectCategory::K2Node_DynamicCast_bSuccess_3' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_SelectCategory, CallFunc_EqualEqual_StrStr_ReturnValue) == 0x0000C1, "Member 'BP_GymEditorWidget_C_SelectCategory::CallFunc_EqualEqual_StrStr_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_SelectCategory, CallFunc_Map_Find_Value_2) == 0x0000C8, "Member 'BP_GymEditorWidget_C_SelectCategory::CallFunc_Map_Find_Value_2' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_SelectCategory, CallFunc_Map_Find_ReturnValue_2) == 0x0000D0, "Member 'BP_GymEditorWidget_C_SelectCategory::CallFunc_Map_Find_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_SelectCategory, K2Node_MakeStruct_Anchors) == 0x0000D8, "Member 'BP_GymEditorWidget_C_SelectCategory::K2Node_MakeStruct_Anchors' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_SelectCategory, CallFunc_SpawnObject_ReturnValue_3) == 0x0000F8, "Member 'BP_GymEditorWidget_C_SelectCategory::CallFunc_SpawnObject_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_SelectCategory, K2Node_MakeStruct_Margin) == 0x000100, "Member 'BP_GymEditorWidget_C_SelectCategory::K2Node_MakeStruct_Margin' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_SelectCategory, K2Node_MakeStruct_Anchors_1) == 0x000110, "Member 'BP_GymEditorWidget_C_SelectCategory::K2Node_MakeStruct_Anchors_1' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_SelectCategory, K2Node_MakeStruct_Margin_1) == 0x000130, "Member 'BP_GymEditorWidget_C_SelectCategory::K2Node_MakeStruct_Margin_1' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_SelectCategory, K2Node_MakeStruct_Anchors_2) == 0x000140, "Member 'BP_GymEditorWidget_C_SelectCategory::K2Node_MakeStruct_Anchors_2' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_SelectCategory, K2Node_MakeStruct_Margin_2) == 0x000160, "Member 'BP_GymEditorWidget_C_SelectCategory::K2Node_MakeStruct_Margin_2' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_SelectCategory, CallFunc_AddChild_ReturnValue) == 0x000170, "Member 'BP_GymEditorWidget_C_SelectCategory::CallFunc_AddChild_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_SelectCategory, CallFunc_AddChild_ReturnValue_1) == 0x000178, "Member 'BP_GymEditorWidget_C_SelectCategory::CallFunc_AddChild_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_SelectCategory, K2Node_DynamicCast_AsCanvas_Panel_Slot) == 0x000180, "Member 'BP_GymEditorWidget_C_SelectCategory::K2Node_DynamicCast_AsCanvas_Panel_Slot' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_SelectCategory, K2Node_DynamicCast_bSuccess_4) == 0x000188, "Member 'BP_GymEditorWidget_C_SelectCategory::K2Node_DynamicCast_bSuccess_4' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_SelectCategory, K2Node_DynamicCast_AsCanvas_Panel_Slot_1) == 0x000190, "Member 'BP_GymEditorWidget_C_SelectCategory::K2Node_DynamicCast_AsCanvas_Panel_Slot_1' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_SelectCategory, K2Node_DynamicCast_bSuccess_5) == 0x000198, "Member 'BP_GymEditorWidget_C_SelectCategory::K2Node_DynamicCast_bSuccess_5' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_SelectCategory, CallFunc_AddChild_ReturnValue_2) == 0x0001A0, "Member 'BP_GymEditorWidget_C_SelectCategory::CallFunc_AddChild_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_SelectCategory, K2Node_DynamicCast_AsCanvas_Panel_Slot_2) == 0x0001A8, "Member 'BP_GymEditorWidget_C_SelectCategory::K2Node_DynamicCast_AsCanvas_Panel_Slot_2' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_SelectCategory, K2Node_DynamicCast_bSuccess_6) == 0x0001B0, "Member 'BP_GymEditorWidget_C_SelectCategory::K2Node_DynamicCast_bSuccess_6' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_SelectCategory, CallFunc_AddChild_ReturnValue_3) == 0x0001B8, "Member 'BP_GymEditorWidget_C_SelectCategory::CallFunc_AddChild_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_SelectCategory, K2Node_DynamicCast_AsCanvas_Panel_Slot_3) == 0x0001C0, "Member 'BP_GymEditorWidget_C_SelectCategory::K2Node_DynamicCast_AsCanvas_Panel_Slot_3' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_SelectCategory, K2Node_DynamicCast_bSuccess_7) == 0x0001C8, "Member 'BP_GymEditorWidget_C_SelectCategory::K2Node_DynamicCast_bSuccess_7' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_SelectCategory, K2Node_MakeStruct_Margin_3) == 0x0001CC, "Member 'BP_GymEditorWidget_C_SelectCategory::K2Node_MakeStruct_Margin_3' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_SelectCategory, K2Node_MakeStruct_Anchors_3) == 0x0001E0, "Member 'BP_GymEditorWidget_C_SelectCategory::K2Node_MakeStruct_Anchors_3' has a wrong offset!");

// Function BP_GymEditorWidget.BP_GymEditorWidget_C.SetCurrentMainPanel
// 0x0028 (0x0028 - 0x0000)
struct BP_GymEditorWidget_C_SetCurrentMainPanel final
{
public:
	class UBP_EditorPiece_C*                      NewMainPanel;                                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UWBP_AssetPropertyEditorWidget_C*       K2Node_DynamicCast_AsWBP_Asset_Property_Editor_Widget; // 0x0008(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UBP_EditorCategoryRow_C*                K2Node_DynamicCast_AsBP_Editor_Category_Row;       // 0x0018(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsMovingAsset_ReturnValue;                // 0x0021(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_GymEditorWidget_C_SetCurrentMainPanel) == 0x000008, "Wrong alignment on BP_GymEditorWidget_C_SetCurrentMainPanel");
static_assert(sizeof(BP_GymEditorWidget_C_SetCurrentMainPanel) == 0x000028, "Wrong size on BP_GymEditorWidget_C_SetCurrentMainPanel");
static_assert(offsetof(BP_GymEditorWidget_C_SetCurrentMainPanel, NewMainPanel) == 0x000000, "Member 'BP_GymEditorWidget_C_SetCurrentMainPanel::NewMainPanel' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_SetCurrentMainPanel, K2Node_DynamicCast_AsWBP_Asset_Property_Editor_Widget) == 0x000008, "Member 'BP_GymEditorWidget_C_SetCurrentMainPanel::K2Node_DynamicCast_AsWBP_Asset_Property_Editor_Widget' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_SetCurrentMainPanel, K2Node_DynamicCast_bSuccess) == 0x000010, "Member 'BP_GymEditorWidget_C_SetCurrentMainPanel::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_SetCurrentMainPanel, K2Node_DynamicCast_AsBP_Editor_Category_Row) == 0x000018, "Member 'BP_GymEditorWidget_C_SetCurrentMainPanel::K2Node_DynamicCast_AsBP_Editor_Category_Row' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_SetCurrentMainPanel, K2Node_DynamicCast_bSuccess_1) == 0x000020, "Member 'BP_GymEditorWidget_C_SetCurrentMainPanel::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_SetCurrentMainPanel, CallFunc_IsMovingAsset_ReturnValue) == 0x000021, "Member 'BP_GymEditorWidget_C_SetCurrentMainPanel::CallFunc_IsMovingAsset_ReturnValue' has a wrong offset!");

// Function BP_GymEditorWidget.BP_GymEditorWidget_C.StartEditingAssetProperty
// 0x0078 (0x0078 - 0x0000)
struct BP_GymEditorWidget_C_StartEditingAssetProperty final
{
public:
	class AGymStaticLevelAsset*                   Asset;                                             // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FText                                   AssetName;                                         // 0x0008(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasRecordId_ReturnValue;                  // 0x0021(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_22[0x6];                                       // 0x0022(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_AssetPropertyEditorWidget_C*       CallFunc_Create_ReturnValue;                       // 0x0028(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UWBP_AssetPropertyEditorWidget_C*       K2Node_DynamicCast_AsWBP_Asset_Property_Editor_Widget; // 0x0030(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_39[0x3];                                       // 0x0039(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FMargin                                K2Node_MakeStruct_Margin;                          // 0x003C(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue;      // 0x004C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4D[0x3];                                       // 0x004D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAnchors                               K2Node_MakeStruct_Anchors;                         // 0x0050(0x0020)(NoDestructor)
	class UCanvasPanelSlot*                       CallFunc_AddChildToCanvas_ReturnValue;             // 0x0070(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_GymEditorWidget_C_StartEditingAssetProperty) == 0x000008, "Wrong alignment on BP_GymEditorWidget_C_StartEditingAssetProperty");
static_assert(sizeof(BP_GymEditorWidget_C_StartEditingAssetProperty) == 0x000078, "Wrong size on BP_GymEditorWidget_C_StartEditingAssetProperty");
static_assert(offsetof(BP_GymEditorWidget_C_StartEditingAssetProperty, Asset) == 0x000000, "Member 'BP_GymEditorWidget_C_StartEditingAssetProperty::Asset' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_StartEditingAssetProperty, AssetName) == 0x000008, "Member 'BP_GymEditorWidget_C_StartEditingAssetProperty::AssetName' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_StartEditingAssetProperty, CallFunc_IsValid_ReturnValue) == 0x000020, "Member 'BP_GymEditorWidget_C_StartEditingAssetProperty::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_StartEditingAssetProperty, CallFunc_HasRecordId_ReturnValue) == 0x000021, "Member 'BP_GymEditorWidget_C_StartEditingAssetProperty::CallFunc_HasRecordId_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_StartEditingAssetProperty, CallFunc_Create_ReturnValue) == 0x000028, "Member 'BP_GymEditorWidget_C_StartEditingAssetProperty::CallFunc_Create_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_StartEditingAssetProperty, K2Node_DynamicCast_AsWBP_Asset_Property_Editor_Widget) == 0x000030, "Member 'BP_GymEditorWidget_C_StartEditingAssetProperty::K2Node_DynamicCast_AsWBP_Asset_Property_Editor_Widget' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_StartEditingAssetProperty, K2Node_DynamicCast_bSuccess) == 0x000038, "Member 'BP_GymEditorWidget_C_StartEditingAssetProperty::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_StartEditingAssetProperty, K2Node_MakeStruct_Margin) == 0x00003C, "Member 'BP_GymEditorWidget_C_StartEditingAssetProperty::K2Node_MakeStruct_Margin' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_StartEditingAssetProperty, CallFunc_EqualEqual_ObjectObject_ReturnValue) == 0x00004C, "Member 'BP_GymEditorWidget_C_StartEditingAssetProperty::CallFunc_EqualEqual_ObjectObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_StartEditingAssetProperty, K2Node_MakeStruct_Anchors) == 0x000050, "Member 'BP_GymEditorWidget_C_StartEditingAssetProperty::K2Node_MakeStruct_Anchors' has a wrong offset!");
static_assert(offsetof(BP_GymEditorWidget_C_StartEditingAssetProperty, CallFunc_AddChildToCanvas_ReturnValue) == 0x000070, "Member 'BP_GymEditorWidget_C_StartEditingAssetProperty::CallFunc_AddChildToCanvas_ReturnValue' has a wrong offset!");

}

