#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_LobbyKeyJoin

#include "Basic.hpp"

#include "BP_LobbyKeyJoin_classes.hpp"
#include "BP_LobbyKeyJoin_parameters.hpp"


namespace SDK
{

// Function BP_LobbyKeyJoin.BP_LobbyKeyJoin_C.BndEvt__BP_LobbyKeyJoin_CancelButton_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UBP_LobbyKeyJoin_C::BndEvt__BP_LobbyKeyJoin_CancelButton_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LobbyKeyJoin_C", "BndEvt__BP_LobbyKeyJoin_CancelButton_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_LobbyKeyJoin.BP_LobbyKeyJoin_C.BndEvt__BP_LobbyKeyJoin_JoinButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UBP_LobbyKeyJoin_C::BndEvt__BP_LobbyKeyJoin_JoinButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LobbyKeyJoin_C", "BndEvt__BP_LobbyKeyJoin_JoinButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_LobbyKeyJoin.BP_LobbyKeyJoin_C.CancelFind
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Success                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_LobbyKeyJoin_C::CancelFind(bool Success)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LobbyKeyJoin_C", "CancelFind");

	Params::BP_LobbyKeyJoin_C_CancelFind Parms{};

	Parms.Success = Success;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_LobbyKeyJoin.BP_LobbyKeyJoin_C.ExecuteUbergraph_BP_LobbyKeyJoin
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_LobbyKeyJoin_C::ExecuteUbergraph_BP_LobbyKeyJoin(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LobbyKeyJoin_C", "ExecuteUbergraph_BP_LobbyKeyJoin");

	Params::BP_LobbyKeyJoin_C_ExecuteUbergraph_BP_LobbyKeyJoin Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_LobbyKeyJoin.BP_LobbyKeyJoin_C.InpActEvt_UIGamepadCancel_K2Node_InputActionEvent_0
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void UBP_LobbyKeyJoin_C::InpActEvt_UIGamepadCancel_K2Node_InputActionEvent_0(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LobbyKeyJoin_C", "InpActEvt_UIGamepadCancel_K2Node_InputActionEvent_0");

	Params::BP_LobbyKeyJoin_C_InpActEvt_UIGamepadCancel_K2Node_InputActionEvent_0 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_LobbyKeyJoin.BP_LobbyKeyJoin_C.JoinComplete
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Success                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_LobbyKeyJoin_C::JoinComplete(bool Success)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LobbyKeyJoin_C", "JoinComplete");

	Params::BP_LobbyKeyJoin_C_JoinComplete Parms{};

	Parms.Success = Success;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_LobbyKeyJoin.BP_LobbyKeyJoin_C.OnFindSessionsCompleteEvent_Event
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<struct FGymSessionSearchResult>  SessionResults                                         (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// bool                                    Successful                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_LobbyKeyJoin_C::OnFindSessionsCompleteEvent_Event(const TArray<struct FGymSessionSearchResult>& SessionResults, bool Successful)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LobbyKeyJoin_C", "OnFindSessionsCompleteEvent_Event");

	Params::BP_LobbyKeyJoin_C_OnFindSessionsCompleteEvent_Event Parms{};

	Parms.SessionResults = std::move(SessionResults);
	Parms.Successful = Successful;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_LobbyKeyJoin.BP_LobbyKeyJoin_C.OnInitialized
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UBP_LobbyKeyJoin_C::OnInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LobbyKeyJoin_C", "OnInitialized");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_LobbyKeyJoin.BP_LobbyKeyJoin_C.OnPreviewMouseButtonDown
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FGeometry                        MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// struct FPointerEvent                    MouseEvent                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UBP_LobbyKeyJoin_C::OnPreviewMouseButtonDown(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LobbyKeyJoin_C", "OnPreviewMouseButtonDown");

	Params::BP_LobbyKeyJoin_C_OnPreviewMouseButtonDown Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_LobbyKeyJoin.BP_LobbyKeyJoin_C.OnVisibilityChanged_Event
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// ESlateVisibility                        InVisibility                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_LobbyKeyJoin_C::OnVisibilityChanged_Event(ESlateVisibility InVisibility)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LobbyKeyJoin_C", "OnVisibilityChanged_Event");

	Params::BP_LobbyKeyJoin_C_OnVisibilityChanged_Event Parms{};

	Parms.InVisibility = InVisibility;

	UObject::ProcessEvent(Func, &Parms);
}

}

