#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PauseMenuWidget

#include "Basic.hpp"

#include "BP_PauseMenuWidget_classes.hpp"
#include "BP_PauseMenuWidget_parameters.hpp"


namespace SDK
{

// Function BP_PauseMenuWidget.BP_PauseMenuWidget_C.BndEvt__BP_PauseMenuWidget_KeyEnableButotn_K2Node_ComponentBoundEvent_11_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UBP_PauseMenuWidget_C::BndEvt__BP_PauseMenuWidget_KeyEnableButotn_K2Node_ComponentBoundEvent_11_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PauseMenuWidget_C", "BndEvt__BP_PauseMenuWidget_KeyEnableButotn_K2Node_ComponentBoundEvent_11_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PauseMenuWidget.BP_PauseMenuWidget_C.BndEvt__BP_PauseMenuWidget_KeyVisibilityButton_K2Node_ComponentBoundEvent_12_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UBP_PauseMenuWidget_C::BndEvt__BP_PauseMenuWidget_KeyVisibilityButton_K2Node_ComponentBoundEvent_12_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PauseMenuWidget_C", "BndEvt__BP_PauseMenuWidget_KeyVisibilityButton_K2Node_ComponentBoundEvent_12_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PauseMenuWidget.BP_PauseMenuWidget_C.BndEvt__BP_PauseMenuWidget_LeaveButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UBP_PauseMenuWidget_C::BndEvt__BP_PauseMenuWidget_LeaveButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PauseMenuWidget_C", "BndEvt__BP_PauseMenuWidget_LeaveButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PauseMenuWidget.BP_PauseMenuWidget_C.BndEvt__BP_PauseMenuWidget_LevelSettingsButton_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UBP_PauseMenuWidget_C::BndEvt__BP_PauseMenuWidget_LevelSettingsButton_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PauseMenuWidget_C", "BndEvt__BP_PauseMenuWidget_LevelSettingsButton_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PauseMenuWidget.BP_PauseMenuWidget_C.BndEvt__BP_PauseMenuWidget_RestartButton_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UBP_PauseMenuWidget_C::BndEvt__BP_PauseMenuWidget_RestartButton_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PauseMenuWidget_C", "BndEvt__BP_PauseMenuWidget_RestartButton_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PauseMenuWidget.BP_PauseMenuWidget_C.BndEvt__BP_PauseMenuWidget_SaveLevelButton_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UBP_PauseMenuWidget_C::BndEvt__BP_PauseMenuWidget_SaveLevelButton_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PauseMenuWidget_C", "BndEvt__BP_PauseMenuWidget_SaveLevelButton_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PauseMenuWidget.BP_PauseMenuWidget_C.BndEvt__BP_PauseMenuWidget_SettingsButton1_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UBP_PauseMenuWidget_C::BndEvt__BP_PauseMenuWidget_SettingsButton1_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PauseMenuWidget_C", "BndEvt__BP_PauseMenuWidget_SettingsButton1_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PauseMenuWidget.BP_PauseMenuWidget_C.BndEvt__BP_PauseMenuWidget_SettingsButton2_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UBP_PauseMenuWidget_C::BndEvt__BP_PauseMenuWidget_SettingsButton2_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PauseMenuWidget_C", "BndEvt__BP_PauseMenuWidget_SettingsButton2_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PauseMenuWidget.BP_PauseMenuWidget_C.BndEvt__BP_PauseMenuWidget_WBP_LobbyVisibilityButton_K2Node_ComponentBoundEvent_10_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UBP_PauseMenuWidget_C::BndEvt__BP_PauseMenuWidget_WBP_LobbyVisibilityButton_K2Node_ComponentBoundEvent_10_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PauseMenuWidget_C", "BndEvt__BP_PauseMenuWidget_WBP_LobbyVisibilityButton_K2Node_ComponentBoundEvent_10_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PauseMenuWidget.BP_PauseMenuWidget_C.BP_OnThumbnailUpdated
// (Event, Public, BlueprintEvent)
// Parameters:
// class FString                           LocalFilePath                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UBP_PauseMenuWidget_C::BP_OnThumbnailUpdated(const class FString& LocalFilePath)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PauseMenuWidget_C", "BP_OnThumbnailUpdated");

	Params::BP_PauseMenuWidget_C_BP_OnThumbnailUpdated Parms{};

	Parms.LocalFilePath = std::move(LocalFilePath);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PauseMenuWidget.BP_PauseMenuWidget_C.BPClose
// (Event, Protected, BlueprintEvent)

void UBP_PauseMenuWidget_C::BPClose()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PauseMenuWidget_C", "BPClose");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PauseMenuWidget.BP_PauseMenuWidget_C.BPHighlightWidget
// (Event, Public, BlueprintEvent)
// Parameters:
// class UWidget*                          Widget                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UBP_PauseMenuWidget_C::BPHighlightWidget(class UWidget* Widget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PauseMenuWidget_C", "BPHighlightWidget");

	Params::BP_PauseMenuWidget_C_BPHighlightWidget Parms{};

	Parms.Widget = Widget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PauseMenuWidget.BP_PauseMenuWidget_C.BPOpen
// (Event, Protected, BlueprintEvent)

void UBP_PauseMenuWidget_C::BPOpen()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PauseMenuWidget_C", "BPOpen");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PauseMenuWidget.BP_PauseMenuWidget_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UBP_PauseMenuWidget_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PauseMenuWidget_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PauseMenuWidget.BP_PauseMenuWidget_C.CustomEvent
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Success                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FGymMapDetailsResult             Details                                                (BlueprintVisible, BlueprintReadOnly, Parm)

void UBP_PauseMenuWidget_C::CustomEvent(bool Success, const struct FGymMapDetailsResult& Details)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PauseMenuWidget_C", "CustomEvent");

	Params::BP_PauseMenuWidget_C_CustomEvent Parms{};

	Parms.Success = Success;
	Parms.Details = std::move(Details);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PauseMenuWidget.BP_PauseMenuWidget_C.ExecuteUbergraph_BP_PauseMenuWidget
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_PauseMenuWidget_C::ExecuteUbergraph_BP_PauseMenuWidget(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PauseMenuWidget_C", "ExecuteUbergraph_BP_PauseMenuWidget");

	Params::BP_PauseMenuWidget_C_ExecuteUbergraph_BP_PauseMenuWidget Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PauseMenuWidget.BP_PauseMenuWidget_C.GatherMapDetails
// (BlueprintCallable, BlueprintEvent)

void UBP_PauseMenuWidget_C::GatherMapDetails()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PauseMenuWidget_C", "GatherMapDetails");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PauseMenuWidget.BP_PauseMenuWidget_C.GatherScoreboardData
// (BlueprintCallable, BlueprintEvent)

void UBP_PauseMenuWidget_C::GatherScoreboardData()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PauseMenuWidget_C", "GatherScoreboardData");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PauseMenuWidget.BP_PauseMenuWidget_C.GetCareerHighlightWidgets
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<class UWidget*>                  Array                                                  (Parm, OutParm, ContainsInstancedReference)

void UBP_PauseMenuWidget_C::GetCareerHighlightWidgets(TArray<class UWidget*>* Array)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PauseMenuWidget_C", "GetCareerHighlightWidgets");

	Params::BP_PauseMenuWidget_C_GetCareerHighlightWidgets Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Array != nullptr)
		*Array = std::move(Parms.Array);
}


// Function BP_PauseMenuWidget.BP_PauseMenuWidget_C.GetHighlightableWidgets
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// TArray<class UWidget*>                  Widgets                                                (Parm, OutParm, ContainsInstancedReference)

void UBP_PauseMenuWidget_C::GetHighlightableWidgets(TArray<class UWidget*>* Widgets)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PauseMenuWidget_C", "GetHighlightableWidgets");

	Params::BP_PauseMenuWidget_C_GetHighlightableWidgets Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Widgets != nullptr)
		*Widgets = std::move(Parms.Widgets);
}


// Function BP_PauseMenuWidget.BP_PauseMenuWidget_C.GetOnlineHighlighableWidgets
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<class UWidget*>                  Widgets                                                (Parm, OutParm, ContainsInstancedReference)

void UBP_PauseMenuWidget_C::GetOnlineHighlighableWidgets(TArray<class UWidget*>* Widgets)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PauseMenuWidget_C", "GetOnlineHighlighableWidgets");

	Params::BP_PauseMenuWidget_C_GetOnlineHighlighableWidgets Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Widgets != nullptr)
		*Widgets = std::move(Parms.Widgets);
}


// Function BP_PauseMenuWidget.BP_PauseMenuWidget_C.GetServerInfo
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FGymServerInfo                   Server_Info                                            (Parm, OutParm)

void UBP_PauseMenuWidget_C::GetServerInfo(struct FGymServerInfo* Server_Info)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PauseMenuWidget_C", "GetServerInfo");

	Params::BP_PauseMenuWidget_C_GetServerInfo Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Server_Info != nullptr)
		*Server_Info = std::move(Parms.Server_Info);
}


// Function BP_PauseMenuWidget.BP_PauseMenuWidget_C.InpActEvt_UIGamepadDown_K2Node_InputActionEvent_1
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void UBP_PauseMenuWidget_C::InpActEvt_UIGamepadDown_K2Node_InputActionEvent_1(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PauseMenuWidget_C", "InpActEvt_UIGamepadDown_K2Node_InputActionEvent_1");

	Params::BP_PauseMenuWidget_C_InpActEvt_UIGamepadDown_K2Node_InputActionEvent_1 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PauseMenuWidget.BP_PauseMenuWidget_C.InpActEvt_UIGamepadInteract_K2Node_InputActionEvent_3
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void UBP_PauseMenuWidget_C::InpActEvt_UIGamepadInteract_K2Node_InputActionEvent_3(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PauseMenuWidget_C", "InpActEvt_UIGamepadInteract_K2Node_InputActionEvent_3");

	Params::BP_PauseMenuWidget_C_InpActEvt_UIGamepadInteract_K2Node_InputActionEvent_3 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PauseMenuWidget.BP_PauseMenuWidget_C.InpActEvt_UIGamepadLeft_K2Node_InputActionEvent_2
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void UBP_PauseMenuWidget_C::InpActEvt_UIGamepadLeft_K2Node_InputActionEvent_2(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PauseMenuWidget_C", "InpActEvt_UIGamepadLeft_K2Node_InputActionEvent_2");

	Params::BP_PauseMenuWidget_C_InpActEvt_UIGamepadLeft_K2Node_InputActionEvent_2 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PauseMenuWidget.BP_PauseMenuWidget_C.InpActEvt_UIGamepadRight_K2Node_InputActionEvent_4
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void UBP_PauseMenuWidget_C::InpActEvt_UIGamepadRight_K2Node_InputActionEvent_4(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PauseMenuWidget_C", "InpActEvt_UIGamepadRight_K2Node_InputActionEvent_4");

	Params::BP_PauseMenuWidget_C_InpActEvt_UIGamepadRight_K2Node_InputActionEvent_4 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PauseMenuWidget.BP_PauseMenuWidget_C.InpActEvt_UIGamepadUp_K2Node_InputActionEvent_0
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void UBP_PauseMenuWidget_C::InpActEvt_UIGamepadUp_K2Node_InputActionEvent_0(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PauseMenuWidget_C", "InpActEvt_UIGamepadUp_K2Node_InputActionEvent_0");

	Params::BP_PauseMenuWidget_C_InpActEvt_UIGamepadUp_K2Node_InputActionEvent_0 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PauseMenuWidget.BP_PauseMenuWidget_C.LeaveToMainMenu
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ConfirmClicked                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_PauseMenuWidget_C::LeaveToMainMenu(bool ConfirmClicked)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PauseMenuWidget_C", "LeaveToMainMenu");

	Params::BP_PauseMenuWidget_C_LeaveToMainMenu Parms{};

	Parms.ConfirmClicked = ConfirmClicked;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PauseMenuWidget.BP_PauseMenuWidget_C.Navigate To Custom Highlightable Down
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWidget*                          FromWidget                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// class UWidget*                          ToWidget                                               (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UBP_PauseMenuWidget_C::Navigate_To_Custom_Highlightable_Down(class UWidget* FromWidget, class UWidget** ToWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PauseMenuWidget_C", "Navigate To Custom Highlightable Down");

	Params::BP_PauseMenuWidget_C_Navigate_To_Custom_Highlightable_Down Parms{};

	Parms.FromWidget = FromWidget;

	UObject::ProcessEvent(Func, &Parms);

	if (ToWidget != nullptr)
		*ToWidget = Parms.ToWidget;
}


// Function BP_PauseMenuWidget.BP_PauseMenuWidget_C.Navigate To Custom Highlightable Left
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWidget*                          FromWidget                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// class UWidget*                          ToWidget                                               (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UBP_PauseMenuWidget_C::Navigate_To_Custom_Highlightable_Left(class UWidget* FromWidget, class UWidget** ToWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PauseMenuWidget_C", "Navigate To Custom Highlightable Left");

	Params::BP_PauseMenuWidget_C_Navigate_To_Custom_Highlightable_Left Parms{};

	Parms.FromWidget = FromWidget;

	UObject::ProcessEvent(Func, &Parms);

	if (ToWidget != nullptr)
		*ToWidget = Parms.ToWidget;
}


// Function BP_PauseMenuWidget.BP_PauseMenuWidget_C.Navigate To Custom Highlightable Right
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWidget*                          FromWidget                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// class UWBP_LobbyKeyText_C*              ToWidget                                               (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UBP_PauseMenuWidget_C::Navigate_To_Custom_Highlightable_Right(class UWidget* FromWidget, class UWBP_LobbyKeyText_C** ToWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PauseMenuWidget_C", "Navigate To Custom Highlightable Right");

	Params::BP_PauseMenuWidget_C_Navigate_To_Custom_Highlightable_Right Parms{};

	Parms.FromWidget = FromWidget;

	UObject::ProcessEvent(Func, &Parms);

	if (ToWidget != nullptr)
		*ToWidget = Parms.ToWidget;
}


// Function BP_PauseMenuWidget.BP_PauseMenuWidget_C.Navigate To Custom Highlightable Up
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWidget*                          FromWidget                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// class UWidget*                          ToWidget                                               (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UBP_PauseMenuWidget_C::Navigate_To_Custom_Highlightable_Up(class UWidget* FromWidget, class UWidget** ToWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PauseMenuWidget_C", "Navigate To Custom Highlightable Up");

	Params::BP_PauseMenuWidget_C_Navigate_To_Custom_Highlightable_Up Parms{};

	Parms.FromWidget = FromWidget;

	UObject::ProcessEvent(Func, &Parms);

	if (ToWidget != nullptr)
		*ToWidget = Parms.ToWidget;
}


// Function BP_PauseMenuWidget.BP_PauseMenuWidget_C.Navigate To Custom Highlightable Widgets
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWidget*                          FromWidget                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// EUINavDirection                         Direction                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    Success                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_PauseMenuWidget_C::Navigate_To_Custom_Highlightable_Widgets(class UWidget* FromWidget, EUINavDirection Direction, bool* Success)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PauseMenuWidget_C", "Navigate To Custom Highlightable Widgets");

	Params::BP_PauseMenuWidget_C_Navigate_To_Custom_Highlightable_Widgets Parms{};

	Parms.FromWidget = FromWidget;
	Parms.Direction = Direction;

	UObject::ProcessEvent(Func, &Parms);

	if (Success != nullptr)
		*Success = Parms.Success;
}


// Function BP_PauseMenuWidget.BP_PauseMenuWidget_C.OnControllerDisconnected
// (Event, Public, BlueprintEvent)

void UBP_PauseMenuWidget_C::OnControllerDisconnected()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PauseMenuWidget_C", "OnControllerDisconnected");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PauseMenuWidget.BP_PauseMenuWidget_C.OnEndSessionCompleteEvent
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Success                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_PauseMenuWidget_C::OnEndSessionCompleteEvent(bool Success)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PauseMenuWidget_C", "OnEndSessionCompleteEvent");

	Params::BP_PauseMenuWidget_C_OnEndSessionCompleteEvent Parms{};

	Parms.Success = Success;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PauseMenuWidget.BP_PauseMenuWidget_C.OnInitialized
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UBP_PauseMenuWidget_C::OnInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PauseMenuWidget_C", "OnInitialized");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PauseMenuWidget.BP_PauseMenuWidget_C.OnInvalidLevel
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_PauseMenuWidget_C::OnInvalidLevel()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PauseMenuWidget_C", "OnInvalidLevel");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PauseMenuWidget.BP_PauseMenuWidget_C.OnLeaderboardReceived_Event
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Success                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FGymLeaderboard                  Leaderboard                                            (BlueprintVisible, BlueprintReadOnly, Parm)

void UBP_PauseMenuWidget_C::OnLeaderboardReceived_Event(bool Success, const struct FGymLeaderboard& Leaderboard)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PauseMenuWidget_C", "OnLeaderboardReceived_Event");

	Params::BP_PauseMenuWidget_C_OnLeaderboardReceived_Event Parms{};

	Parms.Success = Success;
	Parms.Leaderboard = std::move(Leaderboard);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PauseMenuWidget.BP_PauseMenuWidget_C.OnLevelSettingsClosed
// (BlueprintCallable, BlueprintEvent)

void UBP_PauseMenuWidget_C::OnLevelSettingsClosed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PauseMenuWidget_C", "OnLevelSettingsClosed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PauseMenuWidget.BP_PauseMenuWidget_C.OnLevelSettingsNameChanged
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             NewName                                                (BlueprintVisible, BlueprintReadOnly, Parm)

void UBP_PauseMenuWidget_C::OnLevelSettingsNameChanged(const class FText& NewName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PauseMenuWidget_C", "OnLevelSettingsNameChanged");

	Params::BP_PauseMenuWidget_C_OnLevelSettingsNameChanged Parms{};

	Parms.NewName = std::move(NewName);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PauseMenuWidget.BP_PauseMenuWidget_C.OnLevelSettingsPlayClicked
// (BlueprintCallable, BlueprintEvent)

void UBP_PauseMenuWidget_C::OnLevelSettingsPlayClicked()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PauseMenuWidget_C", "OnLevelSettingsPlayClicked");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PauseMenuWidget.BP_PauseMenuWidget_C.OnLevelSettingsPublishChanged
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsPublished                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_PauseMenuWidget_C::OnLevelSettingsPublishChanged(bool IsPublished)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PauseMenuWidget_C", "OnLevelSettingsPublishChanged");

	Params::BP_PauseMenuWidget_C_OnLevelSettingsPublishChanged Parms{};

	Parms.IsPublished = IsPublished;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PauseMenuWidget.BP_PauseMenuWidget_C.OnLevelSettingsSaveLevelClicked
// (BlueprintCallable, BlueprintEvent)

void UBP_PauseMenuWidget_C::OnLevelSettingsSaveLevelClicked()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PauseMenuWidget_C", "OnLevelSettingsSaveLevelClicked");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PauseMenuWidget.BP_PauseMenuWidget_C.OnLevelSettingsTakeThumbnailClicked
// (BlueprintCallable, BlueprintEvent)

void UBP_PauseMenuWidget_C::OnLevelSettingsTakeThumbnailClicked()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PauseMenuWidget_C", "OnLevelSettingsTakeThumbnailClicked");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PauseMenuWidget.BP_PauseMenuWidget_C.OnMapSaved
// (Event, Public, BlueprintEvent)

void UBP_PauseMenuWidget_C::OnMapSaved()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PauseMenuWidget_C", "OnMapSaved");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PauseMenuWidget.BP_PauseMenuWidget_C.OpenLevelSettingsMenu
// (Event, Public, BlueprintEvent)

void UBP_PauseMenuWidget_C::OpenLevelSettingsMenu()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PauseMenuWidget_C", "OpenLevelSettingsMenu");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PauseMenuWidget.BP_PauseMenuWidget_C.PopulateCareerMenu
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UBP_PauseMenuWidget_C::PopulateCareerMenu()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PauseMenuWidget_C", "PopulateCareerMenu");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PauseMenuWidget.BP_PauseMenuWidget_C.PopulateGamemodeCard
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UBP_PauseMenuWidget_C::PopulateGamemodeCard()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PauseMenuWidget_C", "PopulateGamemodeCard");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PauseMenuWidget.BP_PauseMenuWidget_C.PopulateGoalMapTaskList
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UBP_PauseMenuWidget_C::PopulateGoalMapTaskList()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PauseMenuWidget_C", "PopulateGoalMapTaskList");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PauseMenuWidget.BP_PauseMenuWidget_C.PopulateRaceTaskList
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UBP_PauseMenuWidget_C::PopulateRaceTaskList()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PauseMenuWidget_C", "PopulateRaceTaskList");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PauseMenuWidget.BP_PauseMenuWidget_C.SetAdminVisibility
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_PauseMenuWidget_C::SetAdminVisibility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PauseMenuWidget_C", "SetAdminVisibility");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PauseMenuWidget.BP_PauseMenuWidget_C.ToggleKeyVisibility
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_PauseMenuWidget_C::ToggleKeyVisibility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PauseMenuWidget_C", "ToggleKeyVisibility");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PauseMenuWidget.BP_PauseMenuWidget_C.UpdateLevelInfo
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FCustomLevelFileInfo             LevelInfo                                              (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UBP_PauseMenuWidget_C::UpdateLevelInfo(const struct FCustomLevelFileInfo& LevelInfo)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PauseMenuWidget_C", "UpdateLevelInfo");

	Params::BP_PauseMenuWidget_C_UpdateLevelInfo Parms{};

	Parms.LevelInfo = std::move(LevelInfo);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PauseMenuWidget.BP_PauseMenuWidget_C.UpdateServerInfo
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FGymServerInfo                   ServerInfo                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UBP_PauseMenuWidget_C::UpdateServerInfo(const struct FGymServerInfo& ServerInfo)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PauseMenuWidget_C", "UpdateServerInfo");

	Params::BP_PauseMenuWidget_C_UpdateServerInfo Parms{};

	Parms.ServerInfo = std::move(ServerInfo);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PauseMenuWidget.BP_PauseMenuWidget_C.UpdateSessionVisibility
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UBP_PauseMenuWidget_C::UpdateSessionVisibility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PauseMenuWidget_C", "UpdateSessionVisibility");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PauseMenuWidget.BP_PauseMenuWidget_C.UpdateUseKey
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_PauseMenuWidget_C::UpdateUseKey()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PauseMenuWidget_C", "UpdateUseKey");

	UObject::ProcessEvent(Func, nullptr);
}

}

