#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ServerEntryWidget

#include "Basic.hpp"

#include "BP_ServerEntryWidget_classes.hpp"
#include "BP_ServerEntryWidget_parameters.hpp"


namespace SDK
{

// Function BP_ServerEntryWidget.BP_ServerEntryWidget_C.BndEvt__BP_ServerEntryWidget_JoinButton_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature
// (BlueprintEvent)

void UBP_ServerEntryWidget_C::BndEvt__BP_ServerEntryWidget_JoinButton_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ServerEntryWidget_C", "BndEvt__BP_ServerEntryWidget_JoinButton_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ServerEntryWidget.BP_ServerEntryWidget_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UBP_ServerEntryWidget_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ServerEntryWidget_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ServerEntryWidget.BP_ServerEntryWidget_C.ExecuteUbergraph_BP_ServerEntryWidget
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ServerEntryWidget_C::ExecuteUbergraph_BP_ServerEntryWidget(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ServerEntryWidget_C", "ExecuteUbergraph_BP_ServerEntryWidget");

	Params::BP_ServerEntryWidget_C_ExecuteUbergraph_BP_ServerEntryWidget Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ServerEntryWidget.BP_ServerEntryWidget_C.OnJoinServerRequestComplete_Event
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Success                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FString                           JoinUrl                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UBP_ServerEntryWidget_C::OnJoinServerRequestComplete_Event(bool Success, const class FString& JoinUrl)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ServerEntryWidget_C", "OnJoinServerRequestComplete_Event");

	Params::BP_ServerEntryWidget_C_OnJoinServerRequestComplete_Event Parms{};

	Parms.Success = Success;
	Parms.JoinUrl = std::move(JoinUrl);

	UObject::ProcessEvent(Func, &Parms);
}

}

