#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CanvasPlayerBadgeScoreboardWidget

#include "Basic.hpp"

#include "CanvasPlayerBadgeScoreboardWidget_classes.hpp"
#include "CanvasPlayerBadgeScoreboardWidget_parameters.hpp"


namespace SDK
{

// Function CanvasPlayerBadgeScoreboardWidget.CanvasPlayerBadgeScoreboardWidget_C.BndEvt__CanvasPlayerBadgeScoreboardWidget_KickPlayer_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UCanvasPlayerBadgeScoreboardWidget_C::BndEvt__CanvasPlayerBadgeScoreboardWidget_KickPlayer_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CanvasPlayerBadgeScoreboardWidget_C", "BndEvt__CanvasPlayerBadgeScoreboardWidget_KickPlayer_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CanvasPlayerBadgeScoreboardWidget.CanvasPlayerBadgeScoreboardWidget_C.BndEvt__CanvasPlayerBadgeScoreboardWidget_KickPlayer_K2Node_ComponentBoundEvent_2_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UCanvasPlayerBadgeScoreboardWidget_C::BndEvt__CanvasPlayerBadgeScoreboardWidget_KickPlayer_K2Node_ComponentBoundEvent_2_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CanvasPlayerBadgeScoreboardWidget_C", "BndEvt__CanvasPlayerBadgeScoreboardWidget_KickPlayer_K2Node_ComponentBoundEvent_2_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CanvasPlayerBadgeScoreboardWidget.CanvasPlayerBadgeScoreboardWidget_C.BndEvt__CanvasPlayerBadgeScoreboardWidget_KickPlayer_K2Node_ComponentBoundEvent_3_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UCanvasPlayerBadgeScoreboardWidget_C::BndEvt__CanvasPlayerBadgeScoreboardWidget_KickPlayer_K2Node_ComponentBoundEvent_3_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CanvasPlayerBadgeScoreboardWidget_C", "BndEvt__CanvasPlayerBadgeScoreboardWidget_KickPlayer_K2Node_ComponentBoundEvent_3_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CanvasPlayerBadgeScoreboardWidget.CanvasPlayerBadgeScoreboardWidget_C.BndEvt__CanvasPlayerBadgeScoreboardWidget_ToggleEdit_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UCanvasPlayerBadgeScoreboardWidget_C::BndEvt__CanvasPlayerBadgeScoreboardWidget_ToggleEdit_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CanvasPlayerBadgeScoreboardWidget_C", "BndEvt__CanvasPlayerBadgeScoreboardWidget_ToggleEdit_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CanvasPlayerBadgeScoreboardWidget.CanvasPlayerBadgeScoreboardWidget_C.BndEvt__CanvasPlayerBadgeScoreboardWidget_ToggleEdit_K2Node_ComponentBoundEvent_4_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UCanvasPlayerBadgeScoreboardWidget_C::BndEvt__CanvasPlayerBadgeScoreboardWidget_ToggleEdit_K2Node_ComponentBoundEvent_4_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CanvasPlayerBadgeScoreboardWidget_C", "BndEvt__CanvasPlayerBadgeScoreboardWidget_ToggleEdit_K2Node_ComponentBoundEvent_4_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CanvasPlayerBadgeScoreboardWidget.CanvasPlayerBadgeScoreboardWidget_C.BndEvt__CanvasPlayerBadgeScoreboardWidget_ToggleEdit_K2Node_ComponentBoundEvent_5_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UCanvasPlayerBadgeScoreboardWidget_C::BndEvt__CanvasPlayerBadgeScoreboardWidget_ToggleEdit_K2Node_ComponentBoundEvent_5_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CanvasPlayerBadgeScoreboardWidget_C", "BndEvt__CanvasPlayerBadgeScoreboardWidget_ToggleEdit_K2Node_ComponentBoundEvent_5_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CanvasPlayerBadgeScoreboardWidget.CanvasPlayerBadgeScoreboardWidget_C.Destruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UCanvasPlayerBadgeScoreboardWidget_C::Destruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CanvasPlayerBadgeScoreboardWidget_C", "Destruct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CanvasPlayerBadgeScoreboardWidget.CanvasPlayerBadgeScoreboardWidget_C.EditorRightsChanged
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    RightS                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCanvasPlayerBadgeScoreboardWidget_C::EditorRightsChanged(bool RightS)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CanvasPlayerBadgeScoreboardWidget_C", "EditorRightsChanged");

	Params::CanvasPlayerBadgeScoreboardWidget_C_EditorRightsChanged Parms{};

	Parms.RightS = RightS;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CanvasPlayerBadgeScoreboardWidget.CanvasPlayerBadgeScoreboardWidget_C.ExecuteUbergraph_CanvasPlayerBadgeScoreboardWidget
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCanvasPlayerBadgeScoreboardWidget_C::ExecuteUbergraph_CanvasPlayerBadgeScoreboardWidget(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CanvasPlayerBadgeScoreboardWidget_C", "ExecuteUbergraph_CanvasPlayerBadgeScoreboardWidget");

	Params::CanvasPlayerBadgeScoreboardWidget_C_ExecuteUbergraph_CanvasPlayerBadgeScoreboardWidget Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CanvasPlayerBadgeScoreboardWidget.CanvasPlayerBadgeScoreboardWidget_C.SetInfo
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AGymPlayerState*                  Player_0                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UCanvasPlayerBadgeScoreboardWidget_C::SetInfo(class AGymPlayerState* Player_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CanvasPlayerBadgeScoreboardWidget_C", "SetInfo");

	Params::CanvasPlayerBadgeScoreboardWidget_C_SetInfo Parms{};

	Parms.Player_0 = Player_0;

	UObject::ProcessEvent(Func, &Parms);
}

}

