#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GymSprintRules_BP

#include "Basic.hpp"

#include "GYMGAME_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GymSprintRules_BP.GymSprintRules_BP_C
// 0x0000 (0x0160 - 0x0160)
class UGymSprintRules_BP_C final : public UGymSprintRules
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GymSprintRules_BP_C">();
	}
	static class UGymSprintRules_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGymSprintRules_BP_C>();
	}
};
static_assert(alignof(UGymSprintRules_BP_C) == 0x000008, "Wrong alignment on UGymSprintRules_BP_C");
static_assert(sizeof(UGymSprintRules_BP_C) == 0x000160, "Wrong size on UGymSprintRules_BP_C");

}

