#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UDS_CachedProperties

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum UDS_CachedProperties.UDS_CachedProperties
// NumValues: 0x0064
enum class EUDS_CachedProperties : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator3                           = 2,
	NewEnumerator4                           = 3,
	NewEnumerator5                           = 4,
	NewEnumerator6                           = 5,
	NewEnumerator7                           = 6,
	NewEnumerator8                           = 7,
	NewEnumerator9                           = 8,
	NewEnumerator10                          = 9,
	NewEnumerator11                          = 10,
	NewEnumerator12                          = 11,
	NewEnumerator13                          = 12,
	NewEnumerator14                          = 13,
	NewEnumerator15                          = 14,
	NewEnumerator16                          = 15,
	NewEnumerator17                          = 16,
	NewEnumerator20                          = 17,
	NewEnumerator21                          = 18,
	NewEnumerator22                          = 19,
	NewEnumerator23                          = 20,
	NewEnumerator24                          = 21,
	NewEnumerator25                          = 22,
	NewEnumerator26                          = 23,
	NewEnumerator27                          = 24,
	NewEnumerator29                          = 25,
	NewEnumerator30                          = 26,
	NewEnumerator31                          = 27,
	NewEnumerator32                          = 28,
	NewEnumerator33                          = 29,
	NewEnumerator34                          = 30,
	NewEnumerator35                          = 31,
	NewEnumerator36                          = 32,
	NewEnumerator37                          = 33,
	NewEnumerator38                          = 34,
	NewEnumerator39                          = 35,
	NewEnumerator40                          = 36,
	NewEnumerator41                          = 37,
	NewEnumerator42                          = 38,
	NewEnumerator43                          = 39,
	NewEnumerator44                          = 40,
	NewEnumerator45                          = 41,
	NewEnumerator46                          = 42,
	NewEnumerator50                          = 43,
	NewEnumerator51                          = 44,
	NewEnumerator52                          = 45,
	NewEnumerator53                          = 46,
	NewEnumerator54                          = 47,
	NewEnumerator55                          = 48,
	NewEnumerator56                          = 49,
	NewEnumerator57                          = 50,
	NewEnumerator58                          = 51,
	NewEnumerator61                          = 52,
	NewEnumerator62                          = 53,
	NewEnumerator63                          = 54,
	NewEnumerator64                          = 55,
	NewEnumerator65                          = 56,
	NewEnumerator66                          = 57,
	NewEnumerator67                          = 58,
	NewEnumerator68                          = 59,
	NewEnumerator69                          = 60,
	NewEnumerator70                          = 61,
	NewEnumerator71                          = 62,
	NewEnumerator72                          = 63,
	NewEnumerator74                          = 64,
	NewEnumerator75                          = 65,
	NewEnumerator76                          = 66,
	NewEnumerator77                          = 67,
	NewEnumerator79                          = 68,
	NewEnumerator80                          = 69,
	NewEnumerator85                          = 70,
	NewEnumerator89                          = 71,
	NewEnumerator90                          = 72,
	NewEnumerator91                          = 73,
	NewEnumerator97                          = 74,
	NewEnumerator99                          = 75,
	NewEnumerator103                         = 76,
	NewEnumerator105                         = 77,
	NewEnumerator107                         = 78,
	NewEnumerator108                         = 79,
	NewEnumerator109                         = 80,
	NewEnumerator111                         = 81,
	NewEnumerator112                         = 82,
	NewEnumerator113                         = 83,
	NewEnumerator114                         = 84,
	NewEnumerator115                         = 85,
	NewEnumerator116                         = 86,
	NewEnumerator117                         = 87,
	NewEnumerator118                         = 88,
	NewEnumerator119                         = 89,
	NewEnumerator120                         = 90,
	NewEnumerator121                         = 91,
	NewEnumerator123                         = 92,
	NewEnumerator126                         = 93,
	NewEnumerator127                         = 94,
	NewEnumerator128                         = 95,
	NewEnumerator130                         = 96,
	NewEnumerator131                         = 97,
	NewEnumerator132                         = 98,
	UDS_MAX                                  = 99,
};

}

