#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_GameModeContainer_Make

#include "Basic.hpp"

#include "WBP_GameModeContainer_Make_classes.hpp"
#include "WBP_GameModeContainer_Make_parameters.hpp"


namespace SDK
{

// Function WBP_GameModeContainer_Make.WBP_GameModeContainer_Make_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_GameModeContainer_Make_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GameModeContainer_Make_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GameModeContainer_Make.WBP_GameModeContainer_Make_C.ExecuteUbergraph_WBP_GameModeContainer_Make
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_GameModeContainer_Make_C::ExecuteUbergraph_WBP_GameModeContainer_Make(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GameModeContainer_Make_C", "ExecuteUbergraph_WBP_GameModeContainer_Make");

	Params::WBP_GameModeContainer_Make_C_ExecuteUbergraph_WBP_GameModeContainer_Make Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_GameModeContainer_Make.WBP_GameModeContainer_Make_C.GetSelectedGamemode
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FString                           GameModeId                                             (Parm, OutParm, ZeroConstructor, HasGetValueTypeHash)

void UWBP_GameModeContainer_Make_C::GetSelectedGamemode(class FString* GameModeId)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GameModeContainer_Make_C", "GetSelectedGamemode");

	Params::WBP_GameModeContainer_Make_C_GetSelectedGamemode Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (GameModeId != nullptr)
		*GameModeId = std::move(Parms.GameModeId);
}


// Function WBP_GameModeContainer_Make.WBP_GameModeContainer_Make_C.Hover
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWPB_GameModeButton_Make_C*       Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_GameModeContainer_Make_C::Hover(class UWPB_GameModeButton_Make_C* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GameModeContainer_Make_C", "Hover");

	Params::WBP_GameModeContainer_Make_C_Hover Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_GameModeContainer_Make.WBP_GameModeContainer_Make_C.OnHoveredTabButton__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FString                           GamemodeData                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UWBP_GameModeContainer_Make_C::OnHoveredTabButton__DelegateSignature(const class FString& GamemodeData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GameModeContainer_Make_C", "OnHoveredTabButton__DelegateSignature");

	Params::WBP_GameModeContainer_Make_C_OnHoveredTabButton__DelegateSignature Parms{};

	Parms.GamemodeData = std::move(GamemodeData);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_GameModeContainer_Make.WBP_GameModeContainer_Make_C.OnUnhoveredTabButton__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)

void UWBP_GameModeContainer_Make_C::OnUnhoveredTabButton__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GameModeContainer_Make_C", "OnUnhoveredTabButton__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GameModeContainer_Make.WBP_GameModeContainer_Make_C.Unhover
// (BlueprintCallable, BlueprintEvent)

void UWBP_GameModeContainer_Make_C::Unhover()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GameModeContainer_Make_C", "Unhover");

	UObject::ProcessEvent(Func, nullptr);
}

}

