#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_DialogueAnswer

#include "Basic.hpp"

#include "WBP_DialogueAnswer_classes.hpp"
#include "WBP_DialogueAnswer_parameters.hpp"


namespace SDK
{

// Function WBP_DialogueAnswer.WBP_DialogueAnswer_C.Answered__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_DialogueAnswer_C::Answered__DelegateSignature(int32 Index_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DialogueAnswer_C", "Answered__DelegateSignature");

	Params::WBP_DialogueAnswer_C_Answered__DelegateSignature Parms{};

	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_DialogueAnswer.WBP_DialogueAnswer_C.BndEvt__WBP_DialogueAnswer_ButtonObject_K2Node_ComponentBoundEvent_2_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_DialogueAnswer_C::BndEvt__WBP_DialogueAnswer_ButtonObject_K2Node_ComponentBoundEvent_2_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DialogueAnswer_C", "BndEvt__WBP_DialogueAnswer_ButtonObject_K2Node_ComponentBoundEvent_2_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_DialogueAnswer.WBP_DialogueAnswer_C.BndEvt__WBP_DialogueAnswer_ButtonObject_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_DialogueAnswer_C::BndEvt__WBP_DialogueAnswer_ButtonObject_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DialogueAnswer_C", "BndEvt__WBP_DialogueAnswer_ButtonObject_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_DialogueAnswer.WBP_DialogueAnswer_C.BndEvt__WBP_DialogueAnswer_ButtonObject_K2Node_ComponentBoundEvent_4_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_DialogueAnswer_C::BndEvt__WBP_DialogueAnswer_ButtonObject_K2Node_ComponentBoundEvent_4_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DialogueAnswer_C", "BndEvt__WBP_DialogueAnswer_ButtonObject_K2Node_ComponentBoundEvent_4_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_DialogueAnswer.WBP_DialogueAnswer_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_DialogueAnswer_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DialogueAnswer_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_DialogueAnswer.WBP_DialogueAnswer_C.ExecuteUbergraph_WBP_DialogueAnswer
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_DialogueAnswer_C::ExecuteUbergraph_WBP_DialogueAnswer(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DialogueAnswer_C", "ExecuteUbergraph_WBP_DialogueAnswer");

	Params::WBP_DialogueAnswer_C_ExecuteUbergraph_WBP_DialogueAnswer Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_DialogueAnswer.WBP_DialogueAnswer_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_DialogueAnswer_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DialogueAnswer_C", "PreConstruct");

	Params::WBP_DialogueAnswer_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

