#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_DefaultFade

#include "Basic.hpp"

#include "WBP_DefaultFade_classes.hpp"
#include "WBP_DefaultFade_parameters.hpp"


namespace SDK
{

// Function WBP_DefaultFade.WBP_DefaultFade_C.OnFadeBegin
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  FadeDuration                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_DefaultFade_C::OnFadeBegin(double FadeDuration)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DefaultFade_C", "OnFadeBegin");

	Params::WBP_DefaultFade_C_OnFadeBegin Parms{};

	Parms.FadeDuration = FadeDuration;

	UObject::ProcessEvent(Func, &Parms);
}

}

