#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_SpectatorPlaylistWidget

#include "Basic.hpp"

#include "GYMGAME_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_SpectatorPlaylistWidget.WBP_SpectatorPlaylistWidget_C
// 0x0000 (0x0340 - 0x0340)
class UWBP_SpectatorPlaylistWidget_C final : public UGymGuiSpectatorRuleMetaWidget
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_SpectatorPlaylistWidget_C">();
	}
	static class UWBP_SpectatorPlaylistWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_SpectatorPlaylistWidget_C>();
	}
};
static_assert(alignof(UWBP_SpectatorPlaylistWidget_C) == 0x000008, "Wrong alignment on UWBP_SpectatorPlaylistWidget_C");
static_assert(sizeof(UWBP_SpectatorPlaylistWidget_C) == 0x000340, "Wrong size on UWBP_SpectatorPlaylistWidget_C");

}

