#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_TabsTopContainer_Make

#include "Basic.hpp"

#include "WBP_TabsTopContainer_Make_classes.hpp"
#include "WBP_TabsTopContainer_Make_parameters.hpp"


namespace SDK
{

// Function WBP_TabsTopContainer_Make.WBP_TabsTopContainer_Make_C.CompleteButton
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_TabsTopContainer_Make_C::CompleteButton(int32 Index_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TabsTopContainer_Make_C", "CompleteButton");

	Params::WBP_TabsTopContainer_Make_C_CompleteButton Parms{};

	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_TabsTopContainer_Make.WBP_TabsTopContainer_Make_C.LockButton
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_TabsTopContainer_Make_C::LockButton(int32 Index_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TabsTopContainer_Make_C", "LockButton");

	Params::WBP_TabsTopContainer_Make_C_LockButton Parms{};

	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_TabsTopContainer_Make.WBP_TabsTopContainer_Make_C.UnlockButton
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_TabsTopContainer_Make_C::UnlockButton(int32 Index_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TabsTopContainer_Make_C", "UnlockButton");

	Params::WBP_TabsTopContainer_Make_C_UnlockButton Parms{};

	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);
}

}

